### ISSUE TITLE
No Table Of Content from .Rmd file

### ISSUE THREAD

**Issue by gdevailly** [olOwOlo/hugo-theme-even#100]
Thanks for the great theme.
I'm trying to use it through the R package [blogdown](https://bookdown.org/yihui/blogdown/).
It allows to use Rmarkdown files (.Rmd) to generate blog posts.

On the same (default) _even_ blog, posts written in standard .md do have a nice looking automatic Table Of Content, but posts written in .Rmd do not show it.

Sadly I'm not quite confident enough in .js to understand where the issue is coming from. The TOC seems to be generated for the even.js script? Any idea how I can enable the TOC for .Rmd files?

**Comment by olOwOlo** [comment]
> The TOC seems to be generated for the even.js script?

The js script just enhances TOC. TOC is generated by markdown parser.

---

This problem also exists in the `.org` format (#81).  And... unfortunately, I don't know how to solve this problem. 😢
