### ISSUE TITLE
can not show show multi-line and multiple aligned equations correctly

### ISSUE THREAD

**Issue by jdhao** [olOwOlo/hugo-theme-even#105]
I am aware that the theme enables MathJax support. But it seems that right now, multi-line equations and multiple aligned equations are not shown correctly.

## For multi-line equations

```
$$\begin{equation}
\begin{aligned}
a &= b + c \\
  &= d + e + f + g \\
  &= h + i
\end{aligned}
\end{equation}$$
```

It is rendered as 

<img width="403" alt="snipaste_2018-10-12_02-34-33" src="https://user-images.githubusercontent.com/16662357/46825959-63b82a80-cdc7-11e8-9272-d47593d000ea.png">

There are no line breaks between different lines.

## For multiple aligned equations

```
$$\begin{align}
a &= b + c \label{eq3} \\
x &= yz \label{eq4}\\
l &= m - n \label{eq5}
\end{align}$$
```
It can not be rendered at all. The output is 

![image](https://user-images.githubusercontent.com/16662357/46826105-b560b500-cdc7-11e8-8ae4-8e1a826fb9e9.png)

More failed examples can be seen [here](https://jdhao.github.io/2016/01/19/back-propagation-in-mlp-explained/). 

How to make it work?

**Comment by olOwOlo** [comment]
see https://discourse.gohugo.io/search?q=mathjax%20escape

**Comment by panda-z** [comment]
@jdhao You should use the `mmark` processor.

Just add `markup: mmark` at the top of your markdown file.

**Comment by jdhao** [comment]
thanks, I also found that we can use pandoc as external render. we need to change the extention of markdown file to `pdc`  and install pandoc.
