### ISSUE TITLE
Kotlin syntax highlighting

### ISSUE THREAD

**Issue by ming13** [olOwOlo/hugo-theme-even#11]
Seems like Kotlin is not supported, even if `higlight.js` does actually support it.

<img width="776" alt="screen shot 2017-09-30 at 19 29 03" src="https://user-images.githubusercontent.com/200401/31047551-a6d2564a-a615-11e7-9a8a-7bd27fe716bb.png">

**Comment by olOwOlo** [comment]
Kotlin is not in the list of commonly used languages, and i have added it to the `highlight.pack.js`.

BTW, you can download a custom bundle including only the languages you need in this [page](https://highlightjs.org/download/).

**Comment by ming13** [comment]
Thanks, works on `master`!
