### ISSUE TITLE
如何支持AMP？

### ISSUE THREAD

**Issue by trafficMGR** [olOwOlo/hugo-theme-even#110]
Accelerated Mobile Pages！

Hugo自身并不支持AMP选项，gohugo上讨论的一种解决方法是安装一套amp主题，所以这里还必须给even主题加上amp页的link rel。amp主题也要添加canonical页的link rel。

另一种方法就是直接将even主题改装得符合AMP标准。

**Comment by olOwOlo** [comment]
AMP 必须要做另一套，连接两套主题也很麻烦，暂时不考虑支持 _(:з)∠)_
