### ISSUE TITLE
Footnotes in admonition

### ISSUE THREAD

**Issue by panda-z** [olOwOlo/hugo-theme-even#115]
Is it possible to have footnotes in admonition?

The following code will not be rendered as expected:

```
{{% admonition note "NOTE" false %}}
[^1]
{{% /admonition %}}

[^1]: blahblah
```

**Comment by olOwOlo** [comment]
It seems that codes in shortcode has their own scope.

```
{{% admonition note "NOTE" false %}}
bla bla [^1]

[^1]: bla bla
{{% /admonition %}}
```

![image](https://user-images.githubusercontent.com/26087907/50560442-c6242580-0d3b-11e9-930f-2d580fa0ad4b.png)

**Comment by panda-z** [comment]
Thanks for your hint.

There is already a discussion on hugo discourage:
https://discourse.gohugo.io/t/footnote-anchor-inside-shortcode/2742

The maintainer said it is not possible have footnote inside shortcode. So I'll close this issue.
