### ISSUE TITLE
有没有摘要预览功能啊

### ISSUE THREAD

**Issue by baddate** [olOwOlo/hugo-theme-even#116]
就是不用点进去就可以看到简要描述
我试了试description这个front matter，但是好像没有效果

**Comment by linehk** [comment]
在 Markdown 文件加入 `<!--more-->` 单独一行。这行前面的就是简要描述。

**Comment by baddate** [comment]
> 在 Markdown 文件加入 `<!--more-->` 单独一行。这行前面的就是简要描述。

谢谢
