### ISSUE TITLE
添加了 utterances 评论的支持，请问该将 PR 提交到哪个分支？

### ISSUE THREAD

**Issue by bwangelme** [olOwOlo/hugo-theme-even#117]
我在 https://github.com/bwangelme/hugo-theme-even/commit/125e7e97144c4e26b7e14e2c88ce3dfc4a40db39 中添加了 utterances 评论的支持，可以在 [我的博客](https://bwangel.me/about/) 预览效果。

我想提个 PR 过来。看到 https://github.com/olOwOlo/hugo-theme-even/issues/95 中说可以把 PR 提交到 next 分支。但是发现这个仓库好像没有 next 分支，请问该将 PR 提交到哪个分支啊？

**Comment by olOwOlo** [comment]
master 即可
