### ISSUE TITLE
主题颜色不能修改

### ISSUE THREAD

**Issue by pzb568** [olOwOlo/hugo-theme-even#118]
主题内置了五种颜色 ( Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet )，修改/src/css/_variable.scss 文件中 $theme-color-config不生效，把$theme-color-config前面注释去掉还是不能改变主题颜色

**Comment by cizel** [comment]
重新build了吗？

**Comment by olOwOlo** [comment]
需要 build 呢，貌似已经解决了？
还有问题可以重新打开~
