### ISSUE TITLE
插入代码的样式有点问题

### ISSUE THREAD

**Issue by lianluooo** [olOwOlo/hugo-theme-even#119]
![img](https://ws4.sinaimg.cn/large/a74cb9c0ly1fymq3zg71vj20lo08edg8.jpg)

版本是4.0的

**Comment by olOwOlo** [comment]
是同时开启了 chroma 和 highlight.js 吗？

**Comment by lianluoo** [comment]
应该是吧, 我把highlightInClient关了就正常了
