### ISSUE TITLE
语言设置无效

### ISSUE THREAD

**Issue by bequt** [olOwOlo/hugo-theme-even#12]
Language: 语言文件在 /themes/even/data/even/ 目录下。在你的 data 目录下创建一个 even 目录并复制 default.toml 文件到你的 /data/even/ 目录下，之后你可以按照自己需求更改它。
按照步骤设置后，无效。

**Comment by olOwOlo** [comment]
emmm...我这里没问题的说...

![snipaste_20171001_224309](https://user-images.githubusercontent.com/26087907/31055752-21389054-a6fa-11e7-8675-76ba904f5c2c.png)

确定是这样的吗？
