### ISSUE TITLE
畅言评论建议增加sid

### ISSUE THREAD

**Issue by trentzhou** [olOwOlo/hugo-theme-even#121]
有可能一个文章会有多个URL可以访问到，比如：

http://my-site/page
https://my-site/page
http://www.my-site/page
https://www.my-site/page

默认情况下，畅言认为这些是不同的页面。
根据 畅言的文档 http://changyan.kuaizhan.com/static/help/f-source-id.html
我们可以给文章加一个sid，这样即使用不同的URL访问，看到的内容也是一样的。

我觉得很容易修改，只需要改一下 layouts/partials/comments.html，22行变成 `<div id="SOHUCS" sid="{{ .URL }}"></div>`

我简单地测试过了，可以用的。

**Comment by olOwOlo** [comment]
欢迎 PR 😃

**Comment by trentzhou** [comment]
#133
