### ISSUE TITLE
一些浏览器下左上角小按钮样式异常

### ISSUE THREAD

**Issue by RocFang** [olOwOlo/hugo-theme-even#13]
在华为自带的浏览器，以及qq浏览器5.4.0.1100上，左上角的菜单按钮会变成一个横线，而在微信里面，却又是正常的三个横线。

**Comment by RocFang** [comment]
华为某手机自带浏览器：
![1](https://user-images.githubusercontent.com/1741778/31420681-9ec26ab8-ae75-11e7-8dbb-f652603e0b1b.jpg)


QQ浏览器5.4.0.1100
![2](https://user-images.githubusercontent.com/1741778/31420684-a45273d8-ae75-11e7-972c-fbcf1cf305c3.jpg)

**Comment by olOwOlo** [comment]
更新了~
先试试看吧~

**Comment by RocFang** [comment]
赞这速度：）

测试结果：

1. 华为自带的浏览器的问题被修复

2. qq浏览器上还有问题，之前是一个靠顶上面的横线，现在变成两条了，如下图所示：
![image](https://user-images.githubusercontent.com/1741778/31524448-515f3fbc-afec-11e7-9b10-9cd9d17a5ab5.png)

**Comment by RocFang** [comment]
@olOwOlo  辛苦了，作为一个后端程序员目前也帮不上啥忙：）

**Comment by olOwOlo** [comment]
试试[t-dev](https://github.com/olOwOlo/hugo-theme-even/tree/t-dev)分支，或者直接用这个[even.min.css](https://github.com/olOwOlo/hugo-theme-even/blob/t-dev/static/dist/even.min.css)覆盖之前的css\~
不可以的话去[这个网站](http://ie.icoa.cn/)看看内核版本是多少\~
话说qq浏览器5.4.0.1100 用的是系统内核啊，我下了一个表示一切正常\~
顺便推荐一波firefox\~

**Comment by RocFang** [comment]
@olOwOlo  t-dev分支OK了，赞！

你的博客能放一个赞赏页面不，哈哈，这个主题是我在hugo找到的最好看的主题了

**Comment by olOwOlo** [comment]
啊哈哈\~不客气\~

**Comment by RocFang** [comment]
这个问题解决了，close了：）
