### ISSUE TITLE
How to delete RSS icon

### ISSUE THREAD

**Issue by jeshs** [olOwOlo/hugo-theme-even#132]
![image](https://user-images.githubusercontent.com/43285002/51423857-066f1900-1c01-11e9-9b5b-396fc2b7e5f9.png)
How to delete RSS icon above, i had comment all social links in config.toml, but i dont know how to hide the RSS icon, any advice？

**Comment by palistas** [comment]
Hi @jeshs ! Not sure if this is the best way, but I just commented it out in /themes/even/layouts/partials/footer.html file. You need to comment out this piece of code:
`  {{ if .Site.LanguagePrefix -}}
    <a href="{{ .Site.LanguagePrefix | absURL }}/index.xml" type="application/rss+xml" class="iconfont icon-rss" title="rss"></a>
  {{- else -}}
    <a href="{{ .Site.RSSLink }}" type="application/rss+xml" class="iconfont icon-rss" title="rss"></a>
  {{- end }}
`

**Comment by jeshs** [comment]
@palistas thanks a lot!
