### ISSUE TITLE
如何在index里添加一些js

### ISSUE THREAD

**Issue by fanux** [olOwOlo/hugo-theme-even#137]
用一些站点统计工具需要添加js到head中  要怎么做呢

**Comment by olOwOlo** [comment]
可以加载自定义的 js 文件（如下），但是如果一定要出现在 head 中，你可以修改 [head.html](https://github.com/olOwOlo/hugo-theme-even/blob/master/layouts/partials/head.html) 文件

https://github.com/olOwOlo/hugo-theme-even/blob/cd7f705800097659601828bc63bf3f1ea8d19033/exampleSite/config.toml#L107-L110
