### ISSUE TITLE
主页的mathjax渲染不正确

### ISSUE THREAD

**Issue by smsxgz** [olOwOlo/hugo-theme-even#138]
markdown 代码：
```markdown
---
title: "test"
date: 2019-02-17
lastmod: 2019-02-17

mathjax: True
mathjaxEnableSingleDollar: True
---
Inline: $a^2 + b^2 = c^2$

$$ a^2 + b^2 = c^2 $$

<div> $$ a^2 + b^2 = c^2 $$ </div>

<!--more-->


something
something
something
something
```

主页的显示结果：
![image](https://user-images.githubusercontent.com/29827460/52913420-04c86c00-32f9-11e9-8ebd-e56b8bca6f9f.png)

文章具体界面的显示结果：
![image](https://user-images.githubusercontent.com/29827460/52913437-2c1f3900-32f9-11e9-8e09-c2eeed46e396.png)

**Comment by diyzzz** [comment]
### 重现了你的问题，应该是这样解决
* 请在config.toml中将`mathjax = false`改为`mathjax = true`。

### 话说这应该也算是一个bug:)

**Comment by smsxgz** [comment]
多谢！
