### ISSUE TITLE
带有矩阵的 mathjax 双反斜杠换行

### ISSUE THREAD

**Issue by iterateself** [olOwOlo/hugo-theme-even#139]
您好，比如这个 ：
![2019-02-19 08 53 27](https://user-images.githubusercontent.com/40981861/52982972-d72c1180-3423-11e9-86f9-0eaa47841ffc.png)

渲染后是：
![2019-02-19 08 49 16](https://user-images.githubusercontent.com/40981861/52982823-40f7eb80-3423-11e9-811d-00dc7aa444ca.png)

网页源代码是：
![2019-02-19 08 50 19](https://user-images.githubusercontent.com/40981861/52982850-64229b00-3423-11e9-8c1e-ed5e34e7944e.png)

双反斜杠只有一个了。

**Comment by jdhao** [comment]
@iterateself , 这个现象和主题没关系，因为 hugo 默认的 Markdown 引擎先处理 Markdown，反斜杠在 Markdown 中代表转义字符，所以最后 Mathjax 引擎只看到了一个反斜杠。

要想在 hugo 博客中支持 LaTeX，最好用 pandoc 或者 hugo 自带的 mmark 引擎，具体参见 https://jdhao.github.io/2018/10/10/hexo_to_hugo/#%E5%A6%82%E4%BD%95%E5%AE%8C%E7%BE%8E%E6%94%AF%E6%8C%81-latex-%E5%85%AC%E5%BC%8F

**Comment by hoasxyz** [comment]
@jdhao 你好，请问 mmark 方式存在一个问题就是该文章目录不会生成，请问这个有解决办法吗？

**Comment by jdhao** [comment]
@hoasxyz , 是吗，这个问题我倒没有注意到，我倾向于认为你设置错了。如果真有问题，可以给 hugo 报一个 issue。

**Comment by hoasxyz** [comment]
@jdhao 我注意到你的网站里也有我上述的情况，用公式的博文里没有目录。

另外如果设置`markup: mmark`，行内公式也出现问题了，渲染不了……

**Comment by iterateself** [comment]
@jdhao 用了 pandoc，效果很好，感谢！因为用 pandoc 需要改文件名后缀为 pdc，这使得本地编辑的时候 atom 里面不再以 md 格式进行着色，因此：在提交到服务器上的时候， git hook 里面写了一个 py 脚本，在 hugo 处理前把 md 批量全部修改为 pdc , 很赞

**Comment by iterateself** [comment]
@jdhao -_-|| 才发现好像是没有目录的，还有哪里需要设置的吗

**Comment by jdhao** [comment]
@iterateself  @hoasxyz , 好像是没有目录，我等会确认一下（有公式的博客我一般选用 pandoc 处理)，如果有问题，可以在 hugo github repo 报 issue 或者 hugo 论坛问一下。

@iterateself , 关于 pdc 结尾的 Markdown 文件无法使用「语法高亮」的问题，[我使用的是 Sublime Text](https://jdhao.github.io/2017/03/04/Sublime-Windows-Markdown/)（比 Atom 好用 N 倍），可以自己手动选择文件的格式，

![image](https://user-images.githubusercontent.com/16662357/54130260-07773680-444b-11e9-9790-1277ef59432d.png)

**Comment by iterateself** [comment]
@jdhao 谢谢~~

**Comment by jdhao** [comment]
@iterateself @hoasxyz , 似乎 hugo 使用的 blackfriday (mmark 引擎) 不支持 table of contents，我提了一个问题，你们也可以顺便关注一下进展，在[这里](https://discourse.gohugo.io/t/table-of-contents-for-mmark/7713/6)，另外也可以关注 [这里](https://github.com/gohugoio/hugo/issues/3719)。

**Comment by jdhao** [comment]
使用 Pandoc 无法生成 TOC 是因为 hugo 在调用 Pandoc 的时候，只使用了 `--mathjax` 选项，没有使用 `--toc` 选项，具体 code 见 [这里](https://github.com/gohugoio/hugo/blob/master/helpers/content.go#L735), 如果加上 `--toc` 选项应该是可以生成 toc 的。不妨试着加上 `--toc` 选项，然后 [自己编译 hugo](https://github.com/gohugoio/hugo#build-and-install-the-binaries-from-source-advanced-install) 看看能不能生成 TOC。

## 参考 
+ https://github.com/gohugoio/hugo/pull/4060
+ https://stackoverflow.com/questions/37533412/md-with-latex-to-html-with-mathjax-with-pandoc/55106932#55106932

**Comment by hoasxyz** [comment]
@jdhao 谢谢你！

**Comment by iterateself** [comment]
@jdhao 谢谢，佩服呀~

**Comment by mtdcy** [comment]
这个确实是hugo在处理Markdown的问题，官方已经有说明，请使用<div></div>将Mathjax包裹，这样就没有问题
