### ISSUE TITLE
按说明配置后首页无法列出文章列表，手动输入地址可以显示内容

### ISSUE THREAD

**Issue by ghost** [olOwOlo/hugo-theme-even#14]
操作系统 Debian 9

按照说明配置后，`http://localhost:1313/`首页不显示文章内容，但手动输入地址可以显示内容。

以`content/post/my-first-post.md`为例(目录中只有这么一个文件)，手动输入`http://localhost:1313/post/my-first-post/`，可以显示内容。

点击`Archives`，浏览器地址为`http://localhost:1313/post/`，也没有文章列表显示。

`quickstart/config.toml`是按照说明从`even`主题目录中复制过去的，几乎没有更改其中的参数值。

我需要如何操作才能在主页正常显示文章列表(如demo展示的那样)。

**Comment by olOwOlo** [comment]
我试了一次没发现问题惹~ \_(:з)∠)\_ 

1. `hugo new site quickstart`
2. `cd quickstart`
3. `git clone https://github.com/olOwOlo/hugo-theme-even themes/even`
4. 用 `exampleSite/config.toml` 覆盖 `quickstart/config.toml`
5. `hugo new post/my-first-post.md`
    my-first-post.md 的内容：
    ```
    ---
    title: "My First Post"
    date: 2017-10-12T23:52:51+08:00
    draft: true
    ---

    some content.
    ```
6. `hugo server -D`

我的 hugo 版本是 0.29。
`quickstart/layout` 目录下没有别的主题的遗留文件吧？
或者你可以提供一下源文件~

**Comment by kingname** [comment]
我也遇到了相同的问题。我是把Hexo博客的md文件全部直接放到Hugo的content/post文件夹下，结果生成的网站，首页为空。

![image](https://user-images.githubusercontent.com/5440523/32699576-96d997d8-c77d-11e7-903e-fe22237c5e6e.png)
![](http://7sbpmp.com1.z0.glb.clouddn.com/2017-11-12-21-47-28.png)

**Comment by olOwOlo** [comment]
@kingname 表示重现不出来_(:з)∠)_，能否提供一个 md 文件让我试试~~

**Comment by Mintpix** [comment]
I've found the reason why.....

hugo quickstart里面教的是/content/posts 但@olOwOlo 的模板用的是/content/post
大概，感觉还是改成官方的比较好吧

**Comment by olOwOlo** [comment]
@Mintpix 我参考的几个主题也都是用的 post 而不是 posts 呢，现在更改的话也会给更新主题的同学带来麻烦。而且上面的两位小伙伴都是用的 content/post 呢，所以应该不是这个原因。

**Comment by Mintpix** [comment]
@olOwOlo 诶..是我搞错了。但是我一开始也不能render post，后来才发现目录搞错了.

不过感谢一下作者这么漂亮的主题，更不想学前端了，XD

**Comment by narrowizard** [comment]
@olOwOlo 我也遇到了这个问题, 最后发现是目录搞错了.  
建议在readme中加一下说明.

**Comment by yyydao** [comment]
类似的问题，猜测似乎首页对于渲染路径，只能是post。把config.toml拿来后，我的首页也是空白，然后进入archive显示404。查了一下，发现我之前的路径是posts的，之后将下面的配置改成posts

```toml
···
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/posts/"  #原来是post
···
```

这时候，archives能进入，也就是 `http://localhost:1313/posts/`，但是首页依然是空白。

然后我把自己的`posts`目录改成`post`，在把之前config.toml改回原来的`post`。然后都完美跑起来了。

**Comment by binarization** [comment]
我想把 `post` 改成 `archives`，以适应老的链接，但没想到这个主题会限定使用 `post`

**Comment by HouLPcode** [comment]
注意两点 1. content/post 2. hugo server -D 参数

**Comment by monkback** [comment]
> 类似的问题，猜测似乎首页对于渲染路径，只能是post。把config.toml拿来后，我的首页也是空白，然后进入archive显示404。查了一下，发现我之前的路径是posts的，之后将下面的配置改成posts
> 
> ```toml
> ···
> [[menu.main]]
>   name = "Archives"
>   weight = 20
>   identifier = "archives"
>   url = "/posts/"  #原来是post
> ···
> ```
> 
> 这时候，archives能进入，也就是 `http://localhost:1313/posts/`，但是首页依然是空白。
> 
> 然后我把自己的`posts`目录改成`post`，在把之前config.toml改回原来的`post`。然后都完美跑起来了。

确实是，我发现了其他有的主题也是这种情况

**Comment by conn4575** [comment]
我也遇到了。。按照官方文档，文章应该放在 content 目录下都可以吧，这个能不能提供一个配置呢？

**Comment by monkback** [comment]
> 我也遇到了。。按照官方文档，文章应该放在 content 目录下都可以吧，这个能不能提供一个配置呢？

post可以，posts就不行

**Comment by xmasuhai** [comment]
# 配置参数，HTML中可以引用
[params]
  since = "2019"            # Site creation time          # 站点建立时间，必须早于发布文章的事件否则文章不显示

**Comment by xmasuhai** [comment]
# 配置参数，HTML中可以引用
[params]
  since = "2019"            # Site creation time          # 站点建立时间，必须早于发布文章的事件否则文章不显示

**Comment by solider245** [comment]
> > 把config.toml拿来后，我的首页也是空白，然后进入archive显示404。查了一下，发现我之前的路径是posts的，之后将下面的配置改成帖子
> > ```toml
> > ···
> > [[menu.main]]
> >   name = "Archives"
> >   weight = 20
> >   identifier = "archives"
> >   url = "/posts/"  #原来是post
> > ···
> > ```
> > 
> > 
> > 这时候，archives能进入，也就是`http://localhost:1313/posts/`，但是首页依然是空白。
> > 然后我把自己的`posts`目录改成`post`，在把之前config.toml改回原来的`post`。然后都完美跑起来了。
> 
> 确实是，我发现了其他有的主题也是这种情况

尴尬了，我目录没问题，首页也还是没内容。但是归档那边还是有内容的。
![image](https://user-images.githubusercontent.com/16922341/87877413-c3b61900-ca10-11ea-96a6-fec6fcbf599b.png)

还是说不能使用中文标题呢？没道理呀。

**Comment by telzhou618** [comment]
我用了 paper 主题，也是类似的问题，把 posts文件加改成 post ，首页文章列表才显示了。

**Comment by lz0o0** [comment]
blowfish改了目录还是没有...
