### ISSUE TITLE
插入链接时在站点里英文单词被拆开了，不能很好地换行

### ISSUE THREAD

**Issue by hoasxyz** [olOwOlo/hugo-theme-even#141]
Markdown中一般的英文单词在要换行的时候可以留空从而使单词完整，但是插入为链接的话：
```
[accommodation](...)
```
就不一样了，比如当上面的`accommodation`在一行的结尾处的话，链接并不会留空间使单词完整，而是把它从中间拆开了，请问有解决的办法吗？

**Comment by diyzzz** [comment]
这要改markdown语法的编译器吧
想不到办法了:(

**Comment by hoasxyz** [comment]
[这里](https://github.com/hoasxyz/even-website/blob/91eaf9ade/themes/hugo-theme-even/src/css/_partial/_post/_content.scss#L74)更改！
