### ISSUE TITLE
How to add new icon

### ISSUE THREAD

**Issue by smsxgz** [olOwOlo/hugo-theme-even#143]
提问：具体我需要修改哪些文件才能定制自己的social icon呢？
我尝试修改了src/fonts/iconfont/iconfont.svg文件，编译后并没有想要的结果，请问我还需要修改哪些文件，才能使得修改生效呢？
谢谢！

**Comment by olOwOlo** [comment]
目前是使用 https://icomoon.io/ 生成的 icon，你可以导入 iconfont.woff 后修改
