### ISSUE TITLE
项目存在泄漏本机信息的问题，请求联系olOwOlo的方式

### ISSUE THREAD

**Issue by undeadking** [olOwOlo/hugo-theme-even#145]
并不算高危的问题，但是泄漏出去的信息的是否敏感要看使用者自身。就算不打算修bug，也最低限度要表明会泄漏的信息是什么。

翻遍了olOwOlo的commit，没有留有效邮箱，github和blog也没有联系方式，google到的各种同名账号也很久没活动。觉得这个漏洞还是应该先问一下原作者的意见再公布，可以的话私信联系一下我的twitter账号

**Comment by olOwOlo** [comment]
这里是邮箱_(´ཀ`」 ∠)_

undeadking <notifications@github.com>于2019年2月25日 周一16:20写道：

**Comment by undeadking** [comment]
@olOwOlo 上面的消息确实是用邮箱回复的，然而这不是普通邮件组。我只能知道你这个回复确实使用了被github认证的邮箱，然而看不到你的邮件地址，显示发件人为 notifications@github.com

**Comment by olOwOlo** [comment]
o o olowolo233@gmail.com

**Comment by undeadking** [comment]
@olOwOlo  已收到，可以删除邮箱信息了

**Comment by undeadking** [comment]
@olOwOlo 邮件已发送，issues我还是关了吧
