### ISSUE TITLE
您好，菜单进行分类后文章里就没有导航栏了，请问怎么设置？

### ISSUE THREAD

**Issue by chenxuejian** [olOwOlo/hugo-theme-even#147]
您好，菜单进行分类后文章里就没有导航栏了，请问怎么设置？
![image](https://user-images.githubusercontent.com/10387832/53998971-add9e800-417c-11e9-8f3a-fbba6410871c.png)

以下是我的博客：可以看到菜单里我将标签什么的都去掉，换成我自己想要的，但是文章右侧已经没有文章导航了。
![image](https://user-images.githubusercontent.com/10387832/53999026-d95cd280-417c-11e9-9596-ca5ee0877ca9.png)

**Comment by olOwOlo** [comment]
> 对于这个主题，你应该使用 post 而不是 posts，即 hugo new post/some-content.md。

我猜测是这个原因
