### ISSUE TITLE
不同语言代码高亮设置

### ISSUE THREAD

**Issue by hoasxyz** [olOwOlo/hugo-theme-even#148]
您好~因为我平常多用 R 语言而这个主题默认没有这个语言，我如下添加后红色还是太多效果有些不满意：

```scss
  language-r: "R",
```
请问如果我想 R 语言的代码高亮方式和 C 一样的话，我应该怎么做？

**Comment by olOwOlo** [comment]
目前语法高亮的主题确实有很多颜色被重复使用，或许你可以调整一下高亮主题，相关 css 代码如下

https://github.com/olOwOlo/hugo-theme-even/blob/cd7f705800097659601828bc63bf3f1ea8d19033/src/css/_partial/_post/_code.scss#L210-L282

---

相关文档

https://gohugo.io/commands/hugo_gen_chromastyles/?search-input=Chroma#readout
https://help.farbox.com/pygments.html
