### ISSUE TITLE
`div.content-wrapper`始终置于网页最前

### ISSUE THREAD

**Issue by hoasxyz** [olOwOlo/hugo-theme-even#151]
`div.content-wrapper`始终置于网页最前，即使我修改了该`div`的`z-index`。这样在 background 添加一些东西的话就会被这个`div`盖在下面，请问这个有解决办法吗？

**Comment by olOwOlo** [comment]
跟 `.content-wrapper` 应该没关系，应该是 `.slideout-panel`

https://github.com/olOwOlo/hugo-theme-even/blob/cd7f705800097659601828bc63bf3f1ea8d19033/src/css/_partial/_slideout.scss#L18-L23

**Comment by hoasxyz** [comment]
@olOwOlo 谢谢解答~好像是这样的，不过在这里设置`z-index`貌似也不能和`body`中的`background`同级呀...
