### ISSUE TITLE
Preview of a post

### ISSUE THREAD

**Issue by incenger** [olOwOlo/hugo-theme-even#153]
In the demo page of Hugo, we get the preview of a post like this.
![image](https://user-images.githubusercontent.com/29687642/55731648-bdcb3d00-5a44-11e9-9f37-736a2d1f1ead.png)

However, your example site gives this:
![image](https://user-images.githubusercontent.com/29687642/55731760-ef440880-5a44-11e9-9baa-b8d31bae5117.png)

Could you tell me how to adjust the configuration to make the preview of the post looks like the first one? Thanks in advance.

**Comment by olOwOlo** [comment]
see https://gohugo.io/content-management/summaries/#manual-summary-splitting
