### ISSUE TITLE
build warning and missing about page for hugo version 0.55

### ISSUE THREAD

**Issue by jdhao** [olOwOlo/hugo-theme-even#158]
After updating to latest hugo version (version 0.55), when I run `hugo server`, there are some warning messages:

```
Building sites … WARN 2019/04/17 00:34:25 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2019/04/17 00:34:25 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like:
    {{ with .OutputFormats.Get "RSS" }}{{ . RelPermalink }}{{ end }}.
WARN 2019/04/17 00:34:25 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.
```

In the generated blog, the `About` is missing. This may be due to the incompatible behaviour of this theme and latest hugo?

**Comment by mandarvaze** [comment]
@jdhao Missing About page may be unrelated. I see `About` page fine in spite of the warnings.

**Comment by jdhao** [comment]
It is related for some time, at least when I created this issue. After some update of Hugo, the warning message persists, but the `About` page appears now.
