### ISSUE TITLE
如果想让标题加粗要怎么改代码？

### ISSUE THREAD

**Issue by hgt312** [olOwOlo/hugo-theme-even#16]
rt

**Comment by olOwOlo** [comment]
https://github.com/olOwOlo/hugo-theme-even/blob/fa7e44cec87ae2ec0c572cf808976492d486e969/src/css/_custom/_custom.scss#L1-L4

在这个文件里添加下面这行代码
```sass
$post-title-font-weight: bold;
```

编译生成新的 css 文件
```bash
cd ./themes/even/src/
npm install
npm start
```

**Comment by hgt312** [comment]
可以了，非常感谢！
