### ISSUE TITLE
归档页的文章标题会分两行显示

### ISSUE THREAD

**Issue by shuzang** [olOwOlo/hugo-theme-even#166]
如图，归档页的文章标题比较长时，显示时会分两行，应该怎么调整一下让它在一行全部显示
![QQ截图20190510154527](https://user-images.githubusercontent.com/26682846/57511073-ecd21880-733a-11e9-8c4d-c04922f0c063.png)

**Comment by olOwOlo** [comment]
总归会换行的，除非后面的部分截断用省略号了
