### ISSUE TITLE
gitrepo URL for bitbucket is wrong

### ISSUE THREAD

**Issue by mandarvaze** [olOwOlo/hugo-theme-even#169]
The git commit URL generated at the end of the page, next to "LastMod" has path `commit` like `https://bitbucket.org/mandarvaze/mandarvaze_bitbucket_blog_src/commit/5e95136de921eabcb78fde348891e8887f6badd3`

This leads to 404

In the URL above, `commit` needs to be `commits` (note **s** at the end) and then it works.

**Comment by panda-z** [comment]
This issue was introduced by https://github.com/olOwOlo/hugo-theme-even/pull/124

TBH, `commit` should not be hard coded into `gitRepo`.
