### ISSUE TITLE
Examples for creative website header animations using Canvas and JavaScript in Google Search

### ISSUE THREAD

**Issue by JagarYousef** [olOwOlo/hugo-theme-even#170]
I have change the description in config.toml but I still get `Examples for creative website header animations using Canvas and JavaScript` as a description of my website when I search it in google.
I am sure this is not included in config.toml at all so where this meta description is coming from? and why it is not replaced with my description?

**Comment by olOwOlo** [comment]
I don't think this description comes from this theme. Maybe you can review the generated html file.
