### ISSUE TITLE
颜色自定义在本地可用，但在Gitlab Pages中无效，even和Jane均存在此问题

### ISSUE THREAD

**Issue by Howard-00** [olOwOlo/hugo-theme-even#171]

**Comment by olOwOlo** [comment]
或许你需要重新编译生成 css 文件

**Comment by Howard-00** [comment]
> 或许你需要重新编译生成 css 文件

使用git commit -m 'rebuild pages' --allow-empty  ，rebuild仍然不行，要删除某个文件吗

**Comment by Howard-00** [comment]
gitlab的默认ci配置没有extended，目前registry.gitlab.com/dar/hugo:latest是最好的方案
