### ISSUE TITLE
How to change code highlight style to monokai?

### ISSUE THREAD

**Issue by w4-hanggi** [olOwOlo/hugo-theme-even#175]
And maybe add a dark background color to the code segment.

**Comment by olOwOlo** [comment]
https://github.com/olOwOlo/hugo-theme-even/blob/fd1b8d7bc8dcb84d008486562732fbba6b12adad/src/css/_partial/_post/_code.scss#L210-L282

You need to modify the corresponding scss code, see also [Generate Syntax Highlighter CSS](https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css)
