### ISSUE TITLE
Is it possible to set the archive url from `post` to `posts`?

### ISSUE THREAD

**Issue by ycavatars** [olOwOlo/hugo-theme-even#178]
hi,

I'm trying to modify the article url from `xxx/post/article` to `xxx/posts/article`. It works well when I add `post` as prefix in `permalinks` config. However, when I set the archive page url to `post`, the archive page renders nothing. Here's my config:

```
  - name: "Archives"
    weight: 20
    identifier: "archives"
    url: "/posts/"
```

I wonder know is it possible to configure it from `post` to `posts`? Thanks

**Comment by olOwOlo** [comment]
> A **section** cannot be defined or overridden by a front matter parameter – it is strictly derived from the content organization structure.

see https://gohugo.io/content-management/sections/
