### ISSUE TITLE
添加统计代码的最好做法是什么

### ISSUE THREAD

**Issue by RocFang** [olOwOlo/hugo-theme-even#18]
Hi， @olOwOlo ,

一般个人站点经常会加点统计代码，比如cnzz的，我每次是更新本主题后再手动加到footer中去，感觉不太好，不知道其他人是怎么做的，你建议的方式是什么啊？

**Comment by olOwOlo** [comment]
我是新建了一个分支在里面改，有更新就 `git merge master`

**Comment by RocFang** [comment]
嗯嗯，好的，那我也这么干了
