### ISSUE TITLE
TOC 无法更改宽度

### ISSUE THREAD

**Issue by baddate** [olOwOlo/hugo-theme-even#182]
尝试了3种方法：

1. 更改了`/src/css/_variables.scss`里面的`$post-toc-width`不行

2. 在`_custome.scss`中覆盖也不行

3. 直接更改`toc.scss`里的`width`属性也不行

求解！

**Comment by olOwOlo** [comment]
> ## Build
> 
> 如果你更改了 `/src/` 目录下的任意文件，你需要重新编译它们。
> ```bash
> cd ./themes/even/
> # install dependencies
> yarn install
> # build
> yarn build
> ```
> 
> _你需要先安装 **[Yarn](https://yarnpkg.com/)** 和 **[Node.js](https://nodejs.org/)**。_
