### ISSUE TITLE
table head mismatch with table content

### ISSUE THREAD

**Issue by iterateself** [olOwOlo/hugo-theme-even#184]
### 您好~

在 md 中使用 table 的时候，渲染出来的表格的表头与内容偏了一格。。不知道要怎样修改。信息如下：

md内容：

![image](https://user-images.githubusercontent.com/40981861/61998287-55ca6080-b0e0-11e9-8ff2-2c63764cd1e1.png)

网页中显示的：

![image](https://user-images.githubusercontent.com/40981861/61998297-798da680-b0e0-11e9-93c6-1a87d60fc05d.png)

网页源码：

![image](https://user-images.githubusercontent.com/40981861/61998300-85796880-b0e0-11e9-9451-f291e4797705.png)

ps: 

1. 网页地址：http://www.iterate.site/post/01-%E6%95%B0%E5%AD%97%E7%9A%84%E5%BC%A0%E5%8A%9B/02-%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0/01-%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E7%90%86%E8%AE%BA/03-%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0/deeplearning-500-questions/04-%E7%BB%8F%E5%85%B8%E7%BD%91%E7%BB%9C/
2. 渲染时使用的是 pandoc

谢谢~

**Comment by olOwOlo** [comment]
pandoc 生成的表格所带的 class header 和主题定义的 class 冲突了，解决方案：

1. 尝试去除生成出来的 header class
2. 重命名主题中所有 scss 的 header 与模板中 header class 的引用，应该只有以下几处（需重新编译

https://github.com/olOwOlo/hugo-theme-even/blob/fd1b8d7bc8dcb84d008486562732fbba6b12adad/layouts/_default/baseof.html#L20

https://github.com/olOwOlo/hugo-theme-even/blob/fd1b8d7bc8dcb84d008486562732fbba6b12adad/src/css/_partial/_header.scss#L5

https://github.com/olOwOlo/hugo-theme-even/blob/fd1b8d7bc8dcb84d008486562732fbba6b12adad/src/css/_partial/_header.scss#L15
