### ISSUE TITLE
新版hugo所有文章在首页会收入post里。

### ISSUE THREAD

**Issue by w4-hanggi** [olOwOlo/hugo-theme-even#188]

**Comment by fliaping** [comment]
升级hugo到当前最新版0.57.2，已经修复了问题

**Comment by shengwenbai** [comment]
0.58.0又出现了此问题，如图
![image](https://user-images.githubusercontent.com/16640415/64407103-1404e080-d0b6-11e9-8239-fc581633b764.png)

**Comment by w4-hanggi** [comment]
> 0.58.0又出现了此问题，如图
> ![image](https://user-images.githubusercontent.com/16640415/64407103-1404e080-d0b6-11e9-8239-fc581633b764.png)

上次人家说，这个最终都是要改成这样，只是很多人没准备，所以临时改回去了。
现在0.58.0 了，当然又这样喽。

**Comment by alinbxSorcerer** [comment]
> > 0.58.0又出现了此问题，如图
> > ![image](https://user-images.githubusercontent.com/16640415/64407103-1404e080-d0b6-11e9-8239-fc581633b764.png)
> 
> 上次人家说，这个最终都是要改成这样，只是很多人没准备，所以临时改回去了。
> 现在0.58.0 了，当然又这样喽。

没看明白, 升级后就应该这样吗?

**Comment by alinbxSorcerer** [comment]
怎样能改回去?
