### ISSUE TITLE
首页不展示content/post/里面的简短内容。

### ISSUE THREAD

**Issue by slarsar** [olOwOlo/hugo-theme-even#189]
我执行```hugo server```的效果是这样的：

![image](https://user-images.githubusercontent.com/46400566/63156899-52275b00-c048-11e9-92b3-45964867a898.png)

**Comment by slarsar** [comment]
我看到您的demo里的首页是这样的：
![image](https://user-images.githubusercontent.com/46400566/63158863-bea45900-c04c-11e9-8724-fb58c3b7d338.png)

**Comment by slarsar** [comment]
我使用 ```hugo new site mysite```之后，将您的even主题克隆到我的themes目录下，然后复制even下的examplesite的config.toml 和content到我的主目录，执行```hugo server```就看到这个不理想的效果。

**Comment by fliaping** [comment]
我也是这种情况，估计和hugo的版本有关,我的是v0.57.0

**Comment by slarsar** [comment]
> 我也是这种情况，估计和hugo的版本有关,我的是v0.57.0

巧了，我也是v0.57.0, 这位仁兄尝试hugo版本降级了么？我用的archlinux，隐隐约约记得好像今天早上更新了hugo。。。

**Comment by fliaping** [comment]
升级到当前最新版0.57.2，已经修复了问题

**Comment by peach5460** [comment]
升级0.57.2解决问题

**Comment by assLlj** [comment]
我用的arch，hugo版本是0.58.1，也遇到了这个问题，请问有什么解决办法么？
