### ISSUE TITLE
Missing code lines

### ISSUE THREAD

**Issue by timraiswell** [olOwOlo/hugo-theme-even#19]
Hey there! Great theme, thanks so much. I just posted on Stackoverflow an issue I experienced with the theme in blogdown - [link to the issue](https://stackoverflow.com/questions/48154378/)

Basically, after the site build and serve operations are run, the index.html file from the .Rmd post uses </code></pre> to close code chunks on the same line as the remainder of the code chunk. For some reason, this seems to cause the theme to drop a line of code.

**Comment by olOwOlo** [comment]
Hum, in hugo, the last character of code chunk is always a newline character. Anyway, I've modified the code (https://github.com/olOwOlo/hugo-theme-even/commit/5e2df2d9db1de8e52c209b0597bd8b152381e914#diff-5) and now it should work fine. However, if the last line of the code chunk is a blank line then it will be deleted.

**Comment by timraiswell** [comment]
Works perfectly. Many thanks. Love this theme.
