### ISSUE TITLE
Front Matter 中使用 url 参数的文章生成的链接问题

### ISSUE THREAD

**Issue by Azureki** [olOwOlo/hugo-theme-even#190]
首页没有问题，有问题的是`Tags`、`Categories`、`section`。

使用浏览器的调试工具可以看到：
没有使用 url 参数的文章超链接是这样的形式：`href="/post/filename/"`；
使用 url 参数的是这样的：`href="custom-url"`。
然后点击之后会跳转到`http://example.com/some-category/custom-url`。

这不是预期的结果。
根据[这篇文章](https://blog.olowolo.com/post/hugo-quick-start/#hugo-%E4%B8%AD%E7%9A%84%E8%B7%AF%E5%BE%84%E5%88%86%E8%A7%A3)，绝对路径应该是baseurl+url，其中没有category的位置。

我推测，是不是少了个`/`？
其实应该是这样：`href="/custom-url"`？

**Comment by olOwOlo** [comment]
不好意思，没看懂😓

**Comment by Azureki** [comment]
@olOwOlo 
比方说有两篇文章，在front matter中都自定义`categories: [math]`，这两篇文章文件名分别为：`post1.md`，`post2.md`。
post1在front matter中加上`url: custom url`。post2不加。

访问博客：`http://mydomain.com/categories/math/`，会显示这两篇文章。
但是这两篇文章的超链接形式不一样：一个是`href="custom url"`，另一个是`href="/post2"，第二个比第一个多一个"/"。然后点击之后第1个就跳转到`http://mydomain.com/categories/math/custom url`，第2个跳转到`http://mydomain.com/post2`。

我觉得这种行为不一致是不正确的。要么都是在前面加"/"，要么都不加。我个人期望都加。因为在首页的href是都加的。

**Comment by duansheli** [comment]
看了半天 
你描述的是相对路径问题 

比如
```
在页面 https://mirrors.tuna.tsinghua.edu.cn/ceph/ 中有个a链接
<a href="cloudinit/" title="cloudinit">ccccccdddddd/</a>
点击后 地址栏变成了 https://mirrors.tuna.tsinghua.edu.cn/ceph/cloudinit

但如果在页面 https://mirrors.tuna.tsinghua.edu.cn/ceph/aaabbb/ 中有个a链接
<a href="cloudinit/" title="cloudinit">ccccccdddddd/</a>
点击后 地址栏变成了 https://mirrors.tuna.tsinghua.edu.cn/ceph/aaabbb/cloudinit
```
不过没看懂你的 issuse 想说什么问题

问个问题 @olOwOlo 
比如页面 
https://blog.olowolo.com/post/hugo-quick-start/
希望这篇文章的访问链接是   https://blog.olowolo.com/post/hugo-world/ 
该配置什么属性  看了半天没找到 
另外支持 https://blog.olowolo.com/2019/10/10/hugo-world.html  
这种写法吗

**Comment by duansheli** [comment]
找到 /2019/10/10/hugo-world.html 这种写法了

**Comment by gujiakai-dev** [comment]
> 找到 /2019/10/10/hugo-world.html 这种写法了

大哥， 你的hugo博客的永久链接,even主题是什么设置的。我想要.html结尾的效果
