### ISSUE TITLE
首页不展示content/post/里面的简短内容

### ISSUE THREAD

**Issue by assLlj** [olOwOlo/hugo-theme-even#194]
我遇到了和 [这个](https://github.com/olOwOlo/hugo-theme-even/issues/189)一样的问题，这是我的首页
![image](https://user-images.githubusercontent.com/23072555/64546240-de355580-d35c-11e9-8c5a-5a36f9031721.png)
我的hugo版本是0.58.1,使用的arch

**Comment by darkxinyu** [comment]
同问，之前hugo 0.57.0出现过这个问题，0.57.2修复了，现在0.58.1又再次出现

**Comment by lijinglin2019** [comment]
+1

**Comment by lijinglin2019** [comment]
把主题更新到最新的master，恢复了。。。

**Comment by assLlj** [comment]
我更新主题之后也恢复了
