### ISSUE TITLE
使用Pandoc后文章目录(TOC)显示样式错误

### ISSUE THREAD

**Issue by YuxinZhaozyx** [olOwOlo/hugo-theme-even#197]
使用pandoc作为markdown渲染器后post就不显示文章目录了，求助

config.toml中相关设置
```
toc = true         
autoCollapseToc = false 
fancybox = true          
```

**Comment by YuxinZhaozyx** [comment]
参考 https://github.com/olOwOlo/hugo-theme-even/issues/139#issuecomment-471645813
我在hugo源码中加入了 `--toc` 选项，文章确实生成了TOC，但不是以原本侧边悬浮栏的形式，而是作为内容
![image](https://user-images.githubusercontent.com/32972764/65045612-b3b54f00-d991-11e9-9a16-af7f0d0f744e.png)

请问我该怎么将它改成原本侧边栏的样式
谢谢

**Comment by CyrusYip** [comment]
用 `.Rmd` 格式（也是用 pandoc 渲染）目录也是不能生成在侧面，`.org` 格式也有同样的问题。不过这似乎超出了作者的能力范围，只能自己想办法了。
#100 #81
