### ISSUE TITLE
畅言不起作用

### ISSUE THREAD

**Issue by wdssss** [olOwOlo/hugo-theme-even#2]
1. hugo部署在gitlab
2. 自定义域名了. 但这个域名在畅言白名单中.
3.本地server访问能出现畅言(虽然localhost提示不能用)
4.Gitlab服务器上一片空白,没任何提示

**Comment by olOwOlo** [comment]
localhost 应该根本不会加载评论啊... (๑ó⌓ò๑)

> 4.Gitlab服务器上一片空白,没任何提示

是指网页能够正常访问但是看不到畅言么？

你贴一下你的网址我看看吧？

**Comment by wdssss** [comment]
https://taoop.com/hugo/hugo1/
查看网页代码,是可以看到有生成畅言<div>的
然后请看我本地生成的
![shanyan1](https://user-images.githubusercontent.com/9441240/30249602-07acfaaa-9672-11e7-8059-c4cd45bb7baf.png),
顺便问下,打赏功能也没有显示正常.

**Comment by wdssss** [comment]
有了, 改成http协议访问就有了,难道是不支持Https?

**Comment by olOwOlo** [comment]
> (index):272 Mixed Content: The page at 'https://taoop.com/hugo/hugo1/' was loaded over HTTPS, but requested an insecure script 'http://changyan.sohu.com/upload/changyan.js'. This request has been blocked; the content must be served over HTTPS.

被浏览器block了，我等等改成HTTPS

打赏功能没问题啊，你有把enable设置成true么？

**Comment by wdssss** [comment]
打赏功能设置了的.

  [params.reward]                                         # 文章打赏
    enable = true
    wechat = "/pic/wxpay.png"           # 微信二维码
    alipay = "/pic/alipay.jpg"           # 支付宝二维码

**Comment by olOwOlo** [comment]
啊！

你的文章必须放在 content/post 目录才可以正常工作，因为我是针对类型（或者说type或是section）为 post 的文章写的模板。

不在这个目录下的文章会使用默认模板，例如about页面之类的（类似与hexo中的page）
