### ISSUE TITLE
TOC 開啟下 如果markdown的標題有link會有渲染問題

### ISSUE THREAD

**Issue by henrybear327** [olOwOlo/hugo-theme-even#20]
如果使用此代碼(在markdown 的標題中用到link的話)
<img width="630" alt="screen shot 2018-01-13 at 12 31 07 am" src="https://user-images.githubusercontent.com/9054879/34884882-16567a02-f7f9-11e7-83ec-336d5892b438.png">

渲染出來的文字會呈現（重複輸出標題兩次）
<img width="652" alt="screen shot 2018-01-13 at 12 30 49 am" src="https://user-images.githubusercontent.com/9054879/34884941-49f4f1d6-f7f9-11e7-92a1-9387ab639d77.png">

辛苦各位開發者了！

**Comment by olOwOlo** [comment]
修复啦~

**Comment by henrybear327** [comment]
太神啦 ~
謝謝您的幫忙!

真的很喜歡這個theme
希望未來可以幫忙貢獻些
