### ISSUE TITLE
页面宽度 800 * 8393810

### ISSUE THREAD

**Issue by minbaby** [olOwOlo/hugo-theme-even#200]
![image](https://user-images.githubusercontent.com/3191858/66379073-59833900-e9e7-11e9-9dcb-a7136d80c55e.png)

----

osx: 10.15
chrome: 77.0.3865.90

----

ps: Firefox 看了一下没什么问题。 所以是 chrome 兼容性问题吗？

**Comment by kaslr** [comment]
临时解决方案可以看下这里 https://github.com/olOwOlo/hugo-theme-even/issues/201#issuecomment-542196949

好像是新版 macOS webkit 的问题，firefox 是自己的内核所以没有这个问题。

**Comment by minbaby** [comment]
thx

**Comment by zenwan** [comment]
@olOwOlo
