### ISSUE TITLE
macOS上文章列表存在目录时，垂直滚动条会出现无法滚动的问题

### ISSUE THREAD

**Issue by oserz** [olOwOlo/hugo-theme-even#201]
具体可看我网站的文件，在macos上用chrome及safari都有问题

有目录的时候(不正常)
https://oser.space/post/si40098/

无目录的时候(正常)
https://oser.space/post/jdcrawler/

**Comment by aleafboat** [comment]
@oserz  如何做到无目录呢，多谢，我看
无目录的时候(正常)
https://oser.space/post/jdcrawler/ 这个也有标题呀

**Comment by aleafboat** [comment]
toc = true # 是否开启目录
不好意思，阅读文档明白了

**Comment by oserz** [comment]
> @oserz 如何做到无目录呢，多谢，我看
> 无目录的时候(正常)
> https://oser.space/post/jdcrawler/ 这个也有标题呀

不是标题的问题，toc=true，而且在md写法中用了#标识了一二三等多级标题时会渲染出目录来，但有目录时是css中应该存在某个问题导致的macOS下浏览不正常

**Comment by oserz** [comment]
> 一个暂时的 workaround：
> https://github.com/olOwOlo/hugo-theme-even/blob/d39d3e443953caea05510b19fdd7a259c71a0ab3/src/css/_partial/_post/_content.scss#L28
> 
> 这里改成
> 
> ```css
>     vertical-align: initial;
> ```
> 
> 然后重新`yarn build`一下就好了

还没时间分析原因，感谢！！

**Comment by neo0moriarty** [comment]
> 一个暂时的 workaround：
> 
> https://github.com/olOwOlo/hugo-theme-even/blob/d39d3e443953caea05510b19fdd7a259c71a0ab3/src/css/_partial/_post/_content.scss#L28
> 
> 这里改成
> 
> ```css
>     vertical-align: initial;
> ```
> 
> 然后重新`yarn build`一下就好了

macos10.15，碰到同样的问题，chrome和safari都有，firefox没有该问题。这方案可行。
