### ISSUE TITLE
这种首页是如何做的的？

### ISSUE THREAD

**Issue by ahmczsy** [olOwOlo/hugo-theme-even#208]
https://networm.me/

我现在是不想要预览，和他这种类似

**Comment by ahmczsy** [comment]
> 他的 blog 里有写 https://networm.me/2019/03/17/switch-to-hugo-theme-even/

我试了，达不到他这种效果，有没有详细点的。
麻烦你了

**Comment by taizilongxu** [comment]
https://github.com/networm/hugo-theme-even/commit/d3281bf36661392e44abee64685471b05de8afe1

**Comment by ahmczsy** [comment]
> [networm@d3281bf](https://github.com/networm/hugo-theme-even/commit/d3281bf36661392e44abee64685471b05de8afe1)
> 
> 这个是作者仓库, 可以参考

感谢
