### ISSUE TITLE
启用TOC时可以无限下滚且Disqus和Media无法正常加载

### ISSUE THREAD

**Issue by D0zingcat** [olOwOlo/hugo-theme-even#209]
可以参见图片所示，macOS 10.15下Safari和Chrome均出现此问题，如果toc不启用或是没有标题层级的文章则不存在无限下滚和不加在post footer的问题。可见下图：
![WX20191029-181236@2x.png](https://i.loli.net/2019/10/29/FtijsqLRv5TMamG.png)

**Comment by zcong1993** [comment]
同样的问题

**Comment by NicoleMayer** [comment]
同上

**Comment by Edogawa-Konan** [comment]
same question

**Comment by gaopengfei123123** [comment]
同上

**Comment by shellj** [comment]
同样的问题，但似乎 firefox 没问题

**Comment by YuhangCh** [comment]
同样的问题，自己看了半天没发现问题在哪。

**Comment by vinurs** [comment]
😂我今天才发现我也是遇到了同样的问题

**Comment by ld000** [comment]
同样的问题

**Comment by eugenejeonme** [comment]
I created and push [PR#225](https://github.com/olOwOlo/hugo-theme-even/pull/225).
