### ISSUE TITLE
能让标题显示突出一些吗

### ISSUE THREAD

**Issue by toure00** [olOwOlo/hugo-theme-even#213]
![image](https://user-images.githubusercontent.com/33457469/68293790-a717c200-00c9-11ea-98fb-b9143750a86b.png)
如图，标题除了大小，没有其他的特征，标题之间离的近时，看起来会比较混乱，不容易区分，希望能给标题加一点明显的特征，如下划线，或者不一样的颜色

**Comment by vinurs** [comment]
我也想要这个功能😄️

**Comment by CyrusYip** [comment]
关闭折叠目录的功能，然后通过右边的目录的层级判断当前阅读的段落在哪个标题上。

```toml
[params]
  toc = true
  autoCollapseToc = false
```

测试：

```markdown
# 一级标题

一级标题

## 二级标题

二级标题

### 三级标题

三级标题

# 一级标题

一级标题

## 二级标题

二级标题

### 三级标题

三级标题

# 一级标题

一级标题

## 二级标题

二级标题

### 三级标题

三级标题

# 一级标题

一级标题

## 二级标题

二级标题

### 三级标题

三级标题
```

![image](https://user-images.githubusercontent.com/60951091/98329365-0852d800-2033-11eb-968a-4bf75b6cad81.png)
