### ISSUE TITLE
可以支持备案号么?

### ISSUE THREAD

**Issue by oldthreefeng** [olOwOlo/hugo-theme-even#214]
毕竟在国内....

**Comment by colben** [comment]
我直接编辑了 layouts/partials/footer.html 这个文件，在最后面的 span 标签里增加的，如下图：
![图片](https://user-images.githubusercontent.com/7829126/69913518-a9283300-1473-11ea-8714-a758507517d6.png)
直接修改即可，无需重新编译。

**Comment by oldthreefeng** [comment]
> 我直接编辑了 layouts/partials/footer.html 这个文件，在最后面的 span 标签里增加的，如下图：
> ![图片](https://user-images.githubusercontent.com/7829126/69913518-a9283300-1473-11ea-8714-a758507517d6.png)
> 直接修改即可，无需重新编译。

感谢~
