### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by NicoleMayer** [olOwOlo/hugo-theme-even#215]
![image](https://user-images.githubusercontent.com/32037406/68606774-00824700-0464-11ea-9ab0-5c6ef20a376a.png)

版本信息
![image](https://user-images.githubusercontent.com/32037406/68606792-109a2680-0464-11ea-87cf-4304f3986261.png)

使用了当前最新无修改版本 build error 求帮忙

**Comment by kidtang** [comment]
v11.13.0 版本去编译

**Comment by akillcool** [comment]
不是版本问题，是网络问题，node-sass没有下载下来
解决办法：https://segmentfault.com/a/1190000018620589#item-2

**Comment by hustwyk** [comment]
有可能是包版本导致的依赖问题，你可以试试 `yarn upgrade` 升级一下

**Comment by panda-z** [comment]
Even has dropped webpack and switched to Hugo Pipes. I think this issue can be closed.
