### ISSUE TITLE
代码样式有问题

### ISSUE THREAD

**Issue by MaxJohnXiang** [olOwOlo/hugo-theme-even#216]
![image](https://user-images.githubusercontent.com/24894004/68659252-e3d43500-0571-11ea-9424-f608759582f9.png)
![image](https://user-images.githubusercontent.com/24894004/68659291-f5b5d800-0571-11ea-85e4-c61c05d75df9.png)

**Comment by imposing1923** [comment]
请问，你博客的markdown编辑的标题有几级标题区别吗？

**Comment by imposing1923** [comment]
我好像在md文档中，编辑的
```
smith:x:1000:1000:smith,,,:/home/smith:/bin/zsh
```
在博客中显示出来有问题，成了这样
smith❌1000:1000:smith,,,:/home/smith:/bin/zsh

![Uploading blog1.jpg…]()
![Uploading blog2.jpg…]()

**Comment by imposing1923** [comment]
我好像在md文档中，编辑的

smith:x:1000:1000:smith,,,:/home/smith:/bin/zsh
在博客中显示出来有问题，成了这样
smith❌1000:1000:smith,,,:/home/smith:/bin/zsh
![blog1](https://user-images.githubusercontent.com/58097125/70508638-b32fed00-1b69-11ea-9ffc-15f77995911c.jpg)
![blog2](https://user-images.githubusercontent.com/58097125/70508723-b925ce00-1b69-11ea-8ad3-821d200b6cad.jpg)

**Comment by vonhyou** [comment]
`:x:`是emoji表情 ❌ ，在配置文档里把`enableEmoji`改成`false`试试

**Comment by panda-z** [comment]
This is caused by the tab indentation inconsistency between your text editor and hugo code block.

Set tab to 4 spaces in your editor and fix your code indentation.

**Comment by opfanswyx** [comment]
> This is caused by the tab indentation inconsistency between your text editor and hugo code block.
> 
> Set tab to 4 spaces in your editor and fix your code indentation.

您好，hugo 的代码块制表符缩进能否改为 4，需要如何修改呢？

**Comment by woniuxingdong** [comment]
@opfanswyx 我觉得一个可行的方法是把**tab**变为**空格**。

**Comment by opfanswyx** [comment]
> @opfanswyx 我觉得一个可行的方法是把`tab`变为`空格`。

你的意思是敲空格吗？但是比如我有一大段代码，有很多缩进，那要敲非常非常多的空格....

**Comment by woniuxingdong** [comment]
@opfanswyx 可以使用自动转换工具（VSCode之类的都有）。按键时是tab，但文本里面其实是空格。下面是我的vim配置。
```shell
 "Use spaces instead of tabs
 set expandtab
 set tabstop=4
 set shiftwidth=4
 set smarttab
```

**Comment by opfanswyx** [comment]
> @opfanswyx 可以使用自动转换工具（VSCode之类的都有）。按键时是tab，但文本里面其实是空格。下面是我的vimrc中的配置。
> 
> ```
>  "Use spaces instead of tabs
>  set expandtab
>  set tabstop=4
>  set shiftwidth=4
>  set smarttab
> ```
我试了没效果啊，代码里是4，但是前端页面上还是8的空格

**Comment by woniuxingdong** [comment]
@opfanswyx 我的有效。检查下是否有重新build。
![Screenshot from 2020-07-23 00-33-55](https://user-images.githubusercontent.com/5960481/88203022-41ca2800-cc7c-11ea-9fbe-80b0fd3b3ac5.png)

渲染的结果
![Screenshot from 2020-07-23 00-35-17](https://user-images.githubusercontent.com/5960481/88203127-6aeab880-cc7c-11ea-9111-b8026a2423e2.png)

**Comment by opfanswyx** [comment]
> @opfanswyx 我的有效。检查下是否有重新build。
> 
> Vim中
> ![Screenshot from 2020-07-23 00-33-55](https://user-images.githubusercontent.com/5960481/88203022-41ca2800-cc7c-11ea-9fbe-80b0fd3b3ac5.png)
> 
> 渲染的结果
> ![Screenshot from 2020-07-23 00-35-17](https://user-images.githubusercontent.com/5960481/88203127-6aeab880-cc7c-11ea-9111-b8026a2423e2.png)

使用这样的设置后
```
 set expandtab
 set tabstop=4
 set shiftwidth=4
 set smarttab
```
我的还是不行，我在vim里敲击一个tab，到blog渲染还是8个宽度。(我是vim8)
https://atticuslab.com/2020/03/go%E8%AF%AD%E8%A8%80%E6%80%BB%E7%BB%93/

**Comment by woniuxingdong** [comment]
1. 你可以检查下你的markdown。我看到同一个文档上面的代码块，有些缩进是对的。
2. 此外，还看到link的markdown文件，缩进不对的地方就是个tab
3. 检查是不是有cache。可以尝试把hugo生成的目录清掉，再完全 clean build。
