### ISSUE TITLE
shortcode失效

### ISSUE THREAD

**Issue by againest1** [olOwOlo/hugo-theme-even#220]
themes/even没有做任何改动。
config.toml完全照搬examplesite
default.md也照搬examplesite

shortcode不生效

**Comment by panda-z** [comment]
Upstream issue. https://github.com/gohugoio/hugo/issues/6553#issuecomment-560642909

**Comment by againest1** [comment]
https://github.com/gohugoio/hugo/issues/6580#issuecomment-561778523

solved
