### ISSUE TITLE
代码块不显示标题

### ISSUE THREAD

**Issue by duansheli** [olOwOlo/hugo-theme-even#221]
![image](https://user-images.githubusercontent.com/8579595/71435269-46008800-2723-11ea-95d9-c0f6e9d47976.png)

主题的示例中 代码块能显示标题 toml 
我本地安装的这个为啥没有啊

https://blog.olowolo.com/post/hugo-quick-start/#配置-hugo

**Comment by icefed** [comment]
hugo的问题，换老版本

**Comment by lczen** [comment]
请问

> hugo的问题，换老版本
请问换哪个版本的hugo，我的是只能显示二级和三级标题。其它标题显示不了。

**Comment by icefed** [comment]
> 请问
> 
> > hugo的问题，换老版本
> > 请问换哪个版本的hugo，我的是只能显示二级和三级标题。其它标题显示不了。

换0.59
