### ISSUE TITLE
网页底部出现了大量空白

### ISSUE THREAD

**Issue by bwangelme** [olOwOlo/hugo-theme-even#223]
官方的主题预览页面中，https://blog.olowolo.com/example-site/post/even-preview/  在 Chrome 和 Safari 中可以看到评论上面有大量的空白。

![](https://passage-1253400711.cos-website.ap-beijing.myqcloud.com/2020-01-09-030536.png)

**Comment by bwangelme** [comment]
和 https://github.com/olOwOlo/hugo-theme-even/issues/209 是同一个问题。

**Comment by iostalks** [comment]
`src/css/_partial/_post/_content.scss` 文件中第 27-29 行 注释调，再用 webpack 重新编译一下就好了。

**Comment by eugenejeonme** [comment]
I created and push PR#225.

**Comment by olOwOlo** [comment]
closed this in https://github.com/olOwOlo/hugo-theme-even/commit/60844e829b4c97b57744384d48718410c37d697a.
