### ISSUE TITLE
这个主题不更新了吗？

### ISSUE THREAD

**Issue by w4-hanggi** [olOwOlo/hugo-theme-even#224]
hugo 发生了很多变化，但是好像没有更新。

**Comment by bwangelme** [comment]
有新的功能需求可以提 issue/PR 过来，广大网友会帮你review的，review 通过的人多了，作者应该会merge的。

https://github.com/olOwOlo/hugo-theme-even/pull/156

例如我这个PR，等了一个多月，就 merge 了 😂。

**Comment by vinurs** [comment]
😂我也感觉不更新，貌似已经好几个月没动静了

**Comment by olOwOlo** [comment]
😂
