### ISSUE TITLE
请求支持「汉字标准格式」

### ISSUE THREAD

**Issue by AgennyBrof** [olOwOlo/hugo-theme-even#226]
如题，goHugo 原生对中文排版的支持度并不高，尤其当涉及到中西文本混排时常有不优雅的地方出现。因此请求 Even 从主题的层级引入对[汉字标准格式](https://hanzi.pro)这一汉字排版框架的支持，实现更加优雅美观的排版设计。

> 「漢字標準格式」是一個集「語意樣式標準化」「文字設計」「高階排版功能」三大概念的Sass/Stylus、JavaScript排版框架。其專為漢字網頁提供的美觀而標準化的環境，不僅符合傳統閱讀習慣、更為螢幕閱讀提供了既成標準，得以完整解決現今漢字網頁設計的排版需求。
「漢字標準格式」完整支援繁體中文、簡體中文及日文等三個採用漢字的語言文字。

- [项目官网](https://hanzi.pro)

- [GitHub仓库](https://github.com/ethantw/Han)

- 另请参见[中文排版需求](https://www.w3.org/TR/clreq/)

**Comment by xiaohao890809** [comment]
这个真的很棒，点赞
