### ISSUE TITLE
文章中的照片无法居中

### ISSUE THREAD

**Issue by xiaohao890809** [olOwOlo/hugo-theme-even#227]
```
## default
![img](/path/to/img.gif "img")

{{% center %}}
## center
![img](/path/to/img.gif "img")
{{% /center %}}

{{% right %}}
## right
![img](/path/to/img.gif "img")
{{% /right %}}

{{% left %}}
## left
![img](/path/to/img.gif "img")
{{% /left %}}
```

![image](https://user-images.githubusercontent.com/9626465/74084436-18d92080-4aaa-11ea-83dd-20d0d5132588.png)

全部靠左了。。。。
请问怎么解决呢？

**Comment by AgennyBrof** [comment]
极不优雅但是管用的方案👉`<center> ![img](url) </center>`

**Comment by xiaohao890809** [comment]
> 极不优雅但是管用的方案👉`<center> ![img](url) </center>`
> 实在没办法可以应急试试

试了下，不行呢

**Comment by AgennyBrof** [comment]
那这样嘞`{{% figure class="center" src="/path/to/img.gif" alt="img" %}}`

**Comment by xiaohao890809** [comment]
> 那这样嘞`{{% figure class="center" src="/path/to/img.gif" alt="img" %}}`

也不行

**Comment by AgennyBrof** [comment]
可能是 shortcode 失效？你可以参考一下这个
https://github.com/gohugoio/hugo/issues/6580#issuecomment-561778523
~~实在不行可以手动改`hugo`生成的 html （大雾~~

**Comment by xiaohao890809** [comment]
> 可能是 shortcode 失效？你可以参考一下这个
> [gohugoio/hugo#6580 (comment)](https://github.com/gohugoio/hugo/issues/6580#issuecomment-561778523)
> ~实在不行可以手动改`hugo`生成的 html （大雾~

找到原因了，我的hugo版本太高了，导致样式不兼容，降到0.54版本重新生成就可以了，谢谢
