### ISSUE TITLE
这个主题不支持图片描述吗？

### ISSUE THREAD

**Issue by heavenly-zy** [olOwOlo/hugo-theme-even#228]
`![描述](url)`，我这样写之后，只显示图片，没有图片描述呀

**Comment by hoasxyz** [comment]
把鼠标悬浮在图片上，就看得到图片描述了。

**Comment by heavenly-zy** [comment]
> 把鼠标悬浮在图片上，就看得到图片描述了。

鼠标浮上去还是没有，是我哪里没有设置吗

**Comment by momoNorthy** [comment]
不应该是![](url "描述")吗？你那个只能是在图片加载失败的时候显示。

**Comment by olOwOlo** [comment]
`![alt](url "title")`
