### ISSUE TITLE
表格无法正常显示

### ISSUE THREAD

**Issue by jaywhen** [olOwOlo/hugo-theme-even#232]
## 作者你好！非常喜欢这个简洁的主题！
* 但是当我在写表格的时候，渲染出来的表格是这样的：
![isss](https://user-images.githubusercontent.com/50481203/77291223-c5005f00-6d18-11ea-877a-a4f49636b485.jpg)
* markdown源码：
![code](https://user-images.githubusercontent.com/50481203/77291908-1eb55900-6d1a-11ea-8103-b6731b080cbc.jpg)
* 是不是我的front matter 设置的问题：
![ruci](https://user-images.githubusercontent.com/50481203/77291941-32f95600-6d1a-11ea-95ad-aa854503d82e.jpg)

**Comment by jefeerzhang** [comment]
是的，我的表格也出现了这样的问题，无法正常显示，希望能够修复，真的很喜欢这个主题。
