### ISSUE TITLE
Mathjax公式显示错误

### ISSUE THREAD

**Issue by zhengyhn** [olOwOlo/hugo-theme-even#233]
公式:
$$ \sum_{i=1}^{n} (a_ib_i)^2 \le \sum_{i=1}^{n} a_i^2 \sum_{i=1}^{n} b_i^2 $$

编译之后为:
$$ \sum_{i=1}^{n} (a_ib<em>i)^2 \le \sum</em>{i=1}^{n} a<em>i^2 \sum</em>{i=1}^{n} b_i^2 $$</p>

看到解析的时候"_"被<em>替换了，暂时没想出解决办法，先把这个问题提出来。跟这个issue #40 很像。

**Comment by panda-z** [comment]
What version of Hugo do you use? Do you use blackfriday as markdown parser?

Try the newest Hugo with Goldmark parser or add the following front matter to your markdown file:
```
markup: mmark
```

**Comment by woodwm** [comment]
在 [exampleSite/content/post/even-preview.md](https://github.com/olOwOlo/hugo-theme-even/blob/master/exampleSite/content/post/even-preview.md#math) 中，`\( ... \)` 不能正确渲染，需要换成 `\\( ... \\)`，而且 `\begin{align} ... \end{align}` 也不能正确渲染，没有换行和对齐。

**Comment by olOwOlo** [comment]
新版本 hugo 使用 [goldmark](https://gohugo.io/getting-started/configuration-markup/#goldmark) 后应该已经解决了 mathjax 的大多数问题

**Comment by panda-z** [comment]
Goldmark will try to parse math as Markdown. Some characters such as backslash ('\') should be escaped to make the math been properly rendered.

Related upstream issue: https://github.com/gohugoio/hugo/issues/6694

Anyone who wants this feature can upvote the upstream issue.

**Comment by siger-young** [comment]
> 新版本 hugo 使用 [goldmark](https://gohugo.io/getting-started/configuration-markup/#goldmark) 后应该已经解决了 mathjax 的大多数问题

为啥我感觉是带来了一堆新问题……https://blog.olowolo.com/example-site/post/even-preview/

**Comment by woodwm** [comment]
使用最新的 `0.71.1` 编译后，example-site 里的公式依然有我之前说的问题，这个问题似乎存在很久了。`\( ` `\)` 无法识别为公式，`align` 环境也无法正常换行。

<img width="756" alt="image" src="https://user-images.githubusercontent.com/13971199/83309328-a1263180-a211-11ea-89ba-1b5eedc212f9.png">

**Comment by siger-young** [comment]
这应该是 Hugo 的问题，给出一个解决方法：https://cs.yscale.cf/2020/05/29/hugo-fix-markup-math/

**Comment by Luoyayu** [comment]
https://github.com/olOwOlo/hugo-theme-even/issues/233#issuecomment-660157552 refer to [Add goldmark-mathjax](https://github.com/gohugoio/hugo/pull/7435/files)

**Comment by nick-zhy** [comment]
> 这应该是 Hugo 的问题，给出一个解决方法：https://cs.yscale.cf/2020/05/29/hugo-fix-markup-math/

链接失效，还有其他办法吗

**Comment by Luoyayu** [comment]
> > 这应该是 Hugo 的问题，给出一个解决方法：https://cs.yscale.cf/2020/05/29/hugo-fix-markup-math/
> 
> 链接失效，还有其他办法吗

[Add goldmark-mathjax](https://github.com/gohugoio/hugo/pull/7435/files)

**Comment by nick-zhy** [comment]
> > > 这应该是 Hugo 的问题，给出一个解决方法：https://cs.yscale.cf/2020/05/29/hugo-fix-markup-math/
> > 
> > 
> > 链接失效，还有其他办法吗
> 
> [Add goldmark-mathjax](https://github.com/gohugoio/hugo/pull/7435/files)

看不懂这个，不会用....

对不起，我是菜逼，我再找找解决办法，qaq

**Comment by nick-zhy** [comment]
> > > 这应该是 Hugo 的问题，给出一个解决方法：https://cs.yscale.cf/2020/05/29/hugo-fix-markup-math/
> > 
> > 
> > 链接失效，还有其他办法吗
> 
> [Add goldmark-mathjax](https://github.com/gohugoio/hugo/pull/7435/files)

谢谢您的回复，我就说中文哈。我看了下config文件，里面的defaultMarkdownHandler是用的goldmark，但是render出来还是不对头。

**Comment by Luoyayu** [comment]
> > > > 这应该是 Hugo 的问题，给出一个解决方法：https://cs.yscale.cf/2020/05/29/hugo-fix-markup-math/
> > > 
> > > 
> > > 链接失效，还有其他办法吗
> > 
> > 
> > [Add goldmark-mathjax](https://github.com/gohugoio/hugo/pull/7435/files)
> 
> 谢谢您的回复，我就说中文哈。我看了下config文件，里面的defaultMarkdownHandler是用的goldmark，但是render出来还是不对头。

1. 按照 [Add goldmark-mathjax ](https://github.com/gohugoio/hugo/pull/7435/files) 修改 Hugo 的源码
2. 编译&安装Hugo [build-and-install-the-binaries-from-source-advanced-install](https://github.com/gohugoio/hugo#build-and-install-the-binaries-from-source-advanced-install)
