### ISSUE TITLE
Why build section is removed from Readme?

### ISSUE THREAD

**Issue by aasutossh** [olOwOlo/hugo-theme-even#237]
Don't you need to 
```
yarn install
yarn build
```
after changing `/src/` files? No need to build after changing theme?

**Comment by aasutossh** [comment]
Also my github actions fails to build. 
![image](https://user-images.githubusercontent.com/18498932/79185926-fd86ea80-7e37-11ea-8503-fdf30c0da5ae.png)

**Comment by l-lin** [comment]
I think the #130 will answer your question.

**Comment by aasutossh** [comment]
I think it's great.

So, how do I fix the issue? I found hugo just couple days ago, so, don't know much.

Sorry if it is a burden.

**Comment by aasutossh** [comment]
I think it's great.

So, how do I fix the issue? I found hugo just couple days ago, so, don't know much.

Sorry if it is a burden.

**Comment by l-lin** [comment]
See this [Hugo FAQ](https://github.com/gohugoio/hugoDocs/blob/master/content/en/troubleshooting/faq.md#i-get-tocss--this-feature-is-not-available-in-your-current-hugo-version).

**Comment by aasutossh** [comment]
So, I just need hugo extended.

Builds successfully. 
Please update location of _variable.scss on Readme. It's new location is `assets/sass/_variables.scss`. Thank you.

**Comment by aasutossh** [comment]
The github actions build is successful but I lost all theme contents.
The site is live at http://aasutossh.github.io

Looks like plain html.

**Comment by panda-z** [comment]
@aasutossh 

How do you deploy your site? Do you pass `-b <your baseURL>` to hugo?

**Comment by aasutossh** [comment]
I am using github actions. This one in particular. https://github.com/marketplace/actions/hugo-setup#%EF%B8%8F-create-your-workflow

The build command is just `hugo`. I don't pass `minify`.

Also I don't pass `-b <baseURL>` to hugo.

My .yml file looks like this. http://dpaste.com/1H80F80

**Comment by panda-z** [comment]
@aasutossh 

You should add `http://` or `https://` prefix to baseURL in `config.toml`.

**Comment by aasutossh** [comment]
Yes, I had only set `baseURL = "www.aasutossh.com.np"`, I changed that to `baseURL = "http://www.aasutossh.com.np"`, then I remembered I don't interact with my domain, rather than it should be github address. So, I finally changed it to `baseURL = "http://aasutossh.github.io"`, after pushing the change, the theme works beautifully.

Thank you very much for help.
