### ISSUE TITLE
leftover files

### ISSUE THREAD

**Issue by laroche** [olOwOlo/hugo-theme-even#238]
Seems with the newest changes in "master", you can now delete the files
"static/dist/even.26188efa.min.js" and "static/dist/even.c2a46f00.min.css".

best regards and thanks for this great hugo theme,

Florian La Roche

**Comment by laroche** [comment]
Also "static/dist" can be removed completely from the repository. The only other content is "fonts"
and those files are already in "static/fonts".

best regards,

Florian La Roche

**Comment by olOwOlo** [comment]
Thanks for your reminder.
