### ISSUE TITLE
URL error of pictures

### ISSUE THREAD

**Issue by kanglcn** [olOwOlo/hugo-theme-even#239]
The path of a blog is `blog/content/readme.md`, and the path of the picture is `blog/static/d/a.png`.
In the blog I insert the picture by `![name](/d/a.png)`. 

When I set the baseURL as `https://xxxxx.github.io/`, in the article, the URL of the picture is `https://xxxxx.github.io/d/a.png` and all things are OK.

But when I set the baseURL as `http://home.ustc.edu.cn/~lk340621`, the URL of the picture in the blog is `http://home.ustc.edu.cn/d/a.png`. But in fact the URL is `http://home.ustc.edu.cn/~lk340621/d/a.png`. 

So in the blog, the picture can't be quoted right.

[right quate](https://kanglcn.github.io/donations/)
[wrong quate](http://home.ustc.edu.cn/~lk340621/donations/)

**Comment by panda-z** [comment]
@kanglcn Try to add
```
relativeURLS = true
```
and
```
canonifyurls = true
```
to your `config.toml`.

For more information, see:
https://gohugo.io/content-management/urls/

**Comment by kanglcn** [comment]
@panda-z Thank for your reply! But nothing happens after my try. So sad.......

**Comment by panda-z** [comment]
I've tested with `canonifyurls = true` and it works as expected.

Did you put `canonifyurls = true` to the top-level section of your `config.toml`?

**Comment by kanglcn** [comment]
I move `canonifyurls = true` to the beginning of my `config.toml` and it turns to work well!

 Last time I put them at the end and it doesn't work. 

Thank you a lot!
