### ISSUE TITLE
Theme demo broken on the Hugo Themes website

### ISSUE THREAD

**Issue by onedrawingperday** [olOwOlo/hugo-theme-even#241]
Hello @olOwOlo 

I am one of the maintainers of Hugo Themes and I noticed that in the latest deploy your theme's demo failed to generate.

Also I noticed that [recently you migrated](https://github.com/olOwOlo/hugo-theme-even/commit/5657112dfb0e6eac2faa2ae1dc0978ed29030709) to using Hugo Pipes.

However you need to take additional steps to make the demo generate on the Hugo Themes Showcase. See here for detailed instructions: https://github.com/gohugoio/hugoThemes#resources

If you have any questions feel free to ask, otherwise feel free to close this issue once you implement the necessary changes.

**Comment by olOwOlo** [comment]
Thanks for your correction.
