### ISSUE TITLE
[Question] how do you insert nofollow to the example post?

### ISSUE THREAD

**Issue by akiradeveloper** [olOwOlo/hugo-theme-even#247]
I see `<meta name="robots" content="noindex,nofollow">` in the example posts but it is harmful to insert this lines to the real sites then I am investigating how to toggle this line but still no idea.

the line is inserted in-between these two blocks from partials/head.html but it seems impossible to insert the line automatically.

```html
<meta name="renderer" content="webkit" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
```

do you insert the line manually for the example site?

**Comment by olOwOlo** [comment]
I override the layout, see [Hugo's Lookup Order](https://gohugo.io/templates/lookup-order/). This is an expected behaviour. I will remove it, after host the example-site elsewhere.
