### ISSUE TITLE
Maybe the current shortcode example is outdated?

### ISSUE THREAD

**Issue by with9** [olOwOlo/hugo-theme-even#248]
i cant insert music163 according to the example.but when i change `% %` to `< >`
it works.
however,i cant modify the image location

**Comment by panda-z** [comment]
@with9 

Do you use the `mmark` markdown renderer?

**Comment by with9** [comment]
@panda-z  thx!!!,it now works well with mmark.

**Comment by panda-z** [comment]
@with9 

Sadly, `mmark` is deprecated and will be removed in the future. It is not recommended to use `mmark`.

**Comment by with9** [comment]
@panda-z i works with blackFriday as well.it seems that this issue only occurs when useing the default goldmark.

**Comment by panda-z** [comment]
@with9 

For the default `goldmark` markdown renderer, you should add the following to your `config.toml`

```toml
[markup.goldmark.renderer]
  unsafe = true
```

See https://github.com/olOwOlo/hugo-theme-even/issues/235#issuecomment-615315294

**Comment by with9** [comment]
@panda-z thank for your patience, now that everything is going well, I can insert raw html  now.
