### ISSUE TITLE
TOC without h1 headers

### ISSUE THREAD

**Issue by damian-krawczyk** [olOwOlo/hugo-theme-even#249]
Hi @olOwOlo,
My local instance http://localhost:1313/post/even-preview/ run using `hugo server -D` generate TOC starting from H2 headers, ommiting H1 headers on each page. Any tip how can I fix it?

TOC I got:
```
CONTENTS
H2
Paragraphs
Anchor
Footnote
Inline
...
```

TOC on your example site for https://blog.olowolo.com/example-site/post/even-preview/
```
CONTENTS
Markdown
H1
Others
```

**Comment by olOwOlo** [comment]
see https://github.com/olOwOlo/hugo-theme-even/issues/240#issuecomment-613780708

**Comment by damian-krawczyk** [comment]
Thanks for such quick feedback!
