### ISSUE TITLE
中英文切换怎么做？

### ISSUE THREAD

**Issue by bigheadghost** [olOwOlo/hugo-theme-even#25]
如题，怎么自动切换en.toml和zh-CN.toml，目前貌似只采用default.toml

**Comment by olOwOlo** [comment]
本来是没有支持多语言的~
切换等我用 [`i18n`](https://gohugo.io/content-management/multilingual/#translation-of-strings) 重构~

**Comment by olOwOlo** [comment]
已经可以自动切换了~
具体参考 [Language Support](https://github.com/olOwOlo/hugo-theme-even/blob/master/README-zh.md#language-support) 和 [CHANGELOG](https://github.com/olOwOlo/hugo-theme-even/blob/master/CHANGELOG.md#changelog)
