### ISSUE TITLE
菜单栏 ”About“ 可以在i18n中翻译成 ”关于“吗

### ISSUE THREAD

**Issue by hello-piper** [olOwOlo/hugo-theme-even#251]

**Comment by olOwOlo** [comment]
这不是翻译的

https://github.com/olOwOlo/hugo-theme-even/blob/f990236eced6ef0b3b09aa4666d228512790afd2/exampleSite/content/about.md#L1-L4

**Comment by hello-piper** [comment]
我把 about.md 改成 关于.md 就行了吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"olOwOlo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 上午8:10
收件人:&nbsp;"olOwOlo/hugo-theme-even"<hugo-theme-even@noreply.github.com&gt;;
抄送:&nbsp;"慢慢行"<2370344854@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [olOwOlo/hugo-theme-even] 菜单栏 ”About“ 可以在i18n中翻译成 ”关于“吗 (#251)





 
这不是翻译的
 
https://github.com/olOwOlo/hugo-theme-even/blob/f990236eced6ef0b3b09aa4666d228512790afd2/exampleSite/content/about.md#L1-L4

**Comment by olOwOlo** [comment]
```diff
---
- title: "About" 
+ title: "关于" 
 date: 2017-08-20T21:38:52+08:00 
 lastmod: 2017-08-28T21:41:52+08:00 
```

**Comment by hello-piper** [comment]
> ```diff
> ---
> - title: "About" 
> + title: "关于" 
>  date: 2017-08-20T21:38:52+08:00 
>  lastmod: 2017-08-28T21:41:52+08:00 
> ```

好滴好滴 谢谢博主
