### ISSUE TITLE
google_analytics doesn't work correctly

### ISSUE THREAD

**Issue by ximet** [olOwOlo/hugo-theme-even#259]
I've added to .toml config file googleAnalytics value my google analytics code. But I don't have any changes from analytics (I don't have any statics and visitors)

**Comment by panda-z** [comment]
Are you hosting the site with Hugo? GA is disabled locally when hosting with Hugo.

Can you try with another server (such as Nginx)?

**Comment by ximet** [comment]
I use Netlify like a hosting
