### ISSUE TITLE
Inline code in admonition title isn't rendered correctly

### ISSUE THREAD

**Issue by panda-z** [olOwOlo/hugo-theme-even#261]
In admonition title, inline code is rendered as mathjax content.

**Comment by olOwOlo** [comment]
Can you give us an example?

**Comment by panda-z** [comment]
@olOwOlo 

1. Create a new site `hugo new site test`
2. Clone even repository`cd test && git clone https://github.com/olOwOlo/hugo-theme-even.git themes/even`
3. Copy config file from theme with `cp themes/even/exampleSite/config.toml .`
4. Add the following to `config.toml`:
```
[markup.goldmark.renderer]
  unsafe = true
```
4. Create a post with `hugo new post/example.md`
5. Add the following to example.md
```
{{% admonition note "`main`" false %}}
admonition body
{{% /admonition %}}

$$
a+b=c
$$
```
6. Enable mathjax in front matter with `mathjax: true`
7. Run hugo with `hugo server -D`
8. Open a browser and you will see that `main` is processed by mathjax

**Comment by panda-z** [comment]
I think is issue has been resolved. If anyone encounters the same problem, feel free to reopen this issue.
