### ISSUE TITLE
Question: How to implement a different home page

### ISSUE THREAD

**Issue by dathinaios** [olOwOlo/hugo-theme-even#268]
Hello,

Could someone point me to the right direction for changing the home page from the blog index into something else while keeping the index in its own blog menu item? I hacked around without success and a quick pointer would save me loads of time.

Thanks!

**Comment by panda-z** [comment]
Create and put your custom home page into `content/_index.md`.

**Comment by dathinaios** [comment]
Thank you @panda-z . This worked! One last thing if you don't mind. I have renamed the original `index.html` to `blog.html` so that I still use it under a menu item `Blog`. I tried adding it in the menu items in the `config.toml` and although it appears it does not show the posts as it used to.

**Comment by panda-z** [comment]
@dathinaios 

You can implement it with the following steps:

1. Copy file from Even's `layouts/index.html` to your site folder's `layouts/blog/` and rename it to `section.html`.
2. In your site folder, create empty file `content/blog/_index.md`

**Comment by dathinaios** [comment]
@panda-z Thank you for taking the time to help! 🙂
