### ISSUE TITLE
Leave tags/categories as is

### ISSUE THREAD

**Issue by ghraecakter** [olOwOlo/hugo-theme-even#27]
Now in front matter,

```yaml
---
tags: "Configure Even"
---
```

would become `configure-even` in `tags` tab.
It'd be great to leave tags/categories **as is**, i.e.
keep the white space and the upper/lowercase,
because otherwise it's impossible.

I tried to find the setting in [_tags.css](https://github.com/olOwOlo/hugo-theme-even/blob/master/src/css/_partial/_tags.scss) yet failed.
I did find difference between it and [hexo-theme-even](https://github.com/ahonn/hexo-theme-even/blob/master/source/css/_partial/_tags.scss), 
yet which doesn't seem to affect this.
An [example](http://www.swiftyper.com/tags/) of  hexo-theme-even.

Thanks for your awesome work.

**Comment by olOwOlo** [comment]
The name of the tag is generated by hugo, and I have not found any method or variable used to obtain the original name from the [hugo documentation](https://gohugo.io/templates/taxonomy-templates/) .

**Comment by ghraecakter** [comment]
Solved via [Preserve Taxonomy Values](https://gohugo.io/content-management/taxonomies/#preserve-taxonomy-values).

Thanks
