### ISSUE TITLE
文章右侧 未解析到一级目录

### ISSUE THREAD

**Issue by wangqingzh** [olOwOlo/hugo-theme-even#277]
今天刚用唉，遇到这个问题，搜索无果后，在这里提一下。
hugo version: v0.72.0/extended
even: 2020-6-1 最新

**Comment by panda-z** [comment]
https://github.com/olOwOlo/hugo-theme-even/issues/240#issuecomment-613780708

**Comment by wangqingzh** [comment]
炒鸡感谢 大佬做的主题一级棒👍
