### ISSUE TITLE
同步最新的提交后,生成页面出现错误

### ISSUE THREAD

**Issue by peach5460** [olOwOlo/hugo-theme-even#28]
Error while rendering "taxonomy" in "": template:   \layouts\_default\taxonomy.html:4:17: executing "content" at <.Paginate>: error calling Paginate: 'pager size' must be a positive integer

不知道怎么处理???

**Comment by olOwOlo** [comment]
Hugo 版本不够应该会在第一个 Error 提醒你，目前最低要求 [0.35](https://github.com/gohugoio/hugo/releases)
Hugo 版本满足要求应该会打印包括中文的错误信息，具体参考 [CHANGELOG](https://github.com/olOwOlo/hugo-theme-even/blob/master/CHANGELOG.md)

**Comment by peach5460** [comment]
好吧,两个问题:
1,我明明记得升级过0.35...但是不明原因,程序还是0.34
2,# rename archive-paginate,我没注意去掉了下划线...
