### ISSUE TITLE
主题颜色改变不了?

### ISSUE THREAD

**Issue by syaofox** [olOwOlo/hugo-theme-even#281]
修改assets/sass/_variable.scss 
```
// ==============================
// Variables
// ==============================

// ========== Theme Color ========== //
// Config here to change theme color
// Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
$theme-color-config: 'Cobalt Blue';

// Default theme color map
$theme-color-map: (
  'Default': #c05b4d #f8f5ec,
  'Mint Green': #16982B #f5f5f5,
  'Cobalt Blue': #0047AB #f0f2f5,
  'Hot Pink': #FF69B4 #f8f5f5,
  'Dark Violet': #9932CC #f5f4fa
);
```
显示的还是默认的红色,我有哪里没做对吗?

**Comment by ayuayue** [comment]
你解决了吗

**Comment by ayuayue** [comment]
> 修改assets/sass/_variable.scss
> 
> ```
> // ==============================
> // Variables
> // ==============================
> 
> // ========== Theme Color ========== //
> // Config here to change theme color
> // Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
> $theme-color-config: 'Cobalt Blue';
> 
> // Default theme color map
> $theme-color-map: (
>   'Default': #c05b4d #f8f5ec,
>   'Mint Green': #16982B #f5f5f5,
>   'Cobalt Blue': #0047AB #f0f2f5,
>   'Hot Pink': #FF69B4 #f8f5f5,
>   'Dark Violet': #9932CC #f5f4fa
> );
> ```
> 
> 显示的还是默认的红色,我有哪里没做对吗?

我也是
