### ISSUE TITLE
JS Flowchart Diagrams好像没效果

### ISSUE THREAD

**Issue by opfanswyx** [olOwOlo/hugo-theme-even#282]
在我的blog ~~https://atticuslab.com/2015/03/js-flowchart-diagrams/~~ https://atticuslab.com/2020/07/js-sequence-diagrams-test/ 上使用，好像没效果，config.toml正确配置。

**Comment by mkmojo** [comment]
我也碰见了同样的问题。


config.toml
```
  [params.flowchartDiagrams]
    enable = true
    options = ""

  [params.sequenceDiagrams]
    enable = true
    options = "{theme: 'simple'}"
```

**Comment by mkmojo** [comment]
我觉得可能是因为两个原因：
1. code block识别错误
其中code block被hugo引擎识别成了`language-fallback`。Even的代码需要依靠 `language-sequence`来画图。
我怀疑是因为hugo中[这个commit导致的: Add Goldmark as the new default markdown handler](https://github.com/gohugoio/hugo/commit/bfb9613a14ab2d93a4474e5486d22e52a9d5e2b3#diff-d9a8850544c4fdead4479c5d5dc3f844R66)
2. js载入错误
如图，绘画sequence diagram的js库无法被正常load。
![image](https://user-images.githubusercontent.com/1907178/86046479-46a01100-ba1b-11ea-9293-17de747301b6.png)

**Comment by opfanswyx** [comment]
> 我觉得可能是因为两个原因：
> 
> 1. code block识别错误
>    其中code block被hugo引擎识别成了`language-fallback`。Even的代码需要依靠 `language-sequence`来画图。
>    我怀疑是因为hugo中[这个commit导致的: Add Goldmark as the new default markdown handler](https://github.com/gohugoio/hugo/commit/bfb9613a14ab2d93a4474e5486d22e52a9d5e2b3#diff-d9a8850544c4fdead4479c5d5dc3f844R66)
> 2. js载入错误
>    如图，绘画sequence diagram的js库无法被正常load。
>    ![image](https://user-images.githubusercontent.com/1907178/86046479-46a01100-ba1b-11ea-9293-17de747301b6.png)



> 我觉得可能是因为两个原因：
> 
> 1. code block识别错误
>    其中code block被hugo引擎识别成了`language-fallback`。Even的代码需要依靠 `language-sequence`来画图。
>    我怀疑是因为hugo中[这个commit导致的: Add Goldmark as the new default markdown handler](https://github.com/gohugoio/hugo/commit/bfb9613a14ab2d93a4474e5486d22e52a9d5e2b3#diff-d9a8850544c4fdead4479c5d5dc3f844R66)
> 2. js载入错误
>    如图，绘画sequence diagram的js库无法被正常load。
>    ![image](https://user-images.githubusercontent.com/1907178/86046479-46a01100-ba1b-11ea-9293-17de747301b6.png)

抱歉我之前的那个连接有错误，是缓存的public文件，更新了连接后，没有原因2的报错了，我也倾向与你给的原因1，由于不懂前端，不知道怎么处理....

**Comment by mkmojo** [comment]
我在hugo的论坛发了个帖子[问这个问题](https://discourse.gohugo.io/t/code-block-for-custom-language/26650/4)，得到了答复。

你试试把`config.toml`里的和 `pygments` 相关的设置注释掉试试看。

比如把下面这行注释掉
```
# pygmentsCodefencesGuessSyntax = true
```

**Comment by mkmojo** [comment]
@opfanswyx 发现您[新的地址](https://atticuslab.com/2020/07/js-sequence-diagrams-test/)正常显示了，请问您修改了什么设定呀？
![image](https://user-images.githubusercontent.com/1907178/86400712-1eace980-bc77-11ea-9ad1-3a32c892791a.png)

**Comment by opfanswyx** [comment]
您好，首先还是要非常感谢你的帮助，抱歉今天才更你说，还是看了你在hugo的提问，感觉是高亮js的问题，我们blog的配置文件config.toml中默认的是go编写的Chroma，即pygments的那个高亮，同时config.toml还有另一个高亮选项highlight.js，而chroma的pygments与highlight.js不能同时开启，且只有开启了highlight.js这个才会有流程图。

进行了一些列如下选项的排列组合测试，发现如下的配置即可正常哈：
```
pygmentsOptions = ""
ptgmentsCodefences = false
pygmentsUseClasses = false
pygmentsCodefencesGuessSyntax = false

highlightInClient = true #这个在下边
```

**Comment by opfanswyx** [comment]
> @opfanswyx 发现您[新的地址](https://atticuslab.com/2020/07/js-sequence-diagrams-test/)正常显示了，请问您修改了什么设定呀？
> ![image](https://user-images.githubusercontent.com/1907178/86400712-1eace980-bc77-11ea-9ad1-3a32c892791a.png)

您好，首先还是要非常感谢你的帮助，抱歉今天才更你说，还是看了你在hugo的提问，感觉是高亮js的问题，我们blog的配置文件`config.toml`中默认的是go编写的`Chroma`，即`pygments`的那个高亮，同时`config.toml`还有另一个高亮选项`highlight.js`，而chroma的`pygments`与`highlight.js`不能同时开启，且只有开启了`highlight.js`这个才会有流程图。

进行了一些列如下选项的排列组合测试，发现是下面的配置，流程图即可正常使用哈：
```
pygmentsOptions = ""
ptgmentsCodefences = false
pygmentsUseClasses = false
pygmentsCodefencesGuessSyntax = false

highlightInClient = true #这个在下边
```

**Comment by mkmojo** [comment]
> > @opfanswyx 发现您[新的地址](https://atticuslab.com/2020/07/js-sequence-diagrams-test/)正常显示了，请问您修改了什么设定呀？
> > ![image](https://user-images.githubusercontent.com/1907178/86400712-1eace980-bc77-11ea-9ad1-3a32c892791a.png)
> 
> 您好，首先还是要非常感谢你的帮助，抱歉今天才更你说，还是看了你在hugo的提问，感觉是高亮js的问题，我们blog的配置文件`config.toml`中默认的是go编写的`Chroma`，即`pygments`的那个高亮，同时`config.toml`还有另一个高亮选项`highlight.js`，而chroma的`pygments`与`highlight.js`不能同时开启，且只有开启了`highlight.js`这个才会有流程图。
> 
> 进行了一些列如下选项的排列组合测试，发现是下面的配置，流程图即可正常使用哈：
> 
> ```
> pygmentsOptions = ""
> ptgmentsCodefences = false
> pygmentsUseClasses = false
> pygmentsCodefencesGuessSyntax = false
> 
> highlightInClient = true #这个在下边
> ```

果然可以了，谢谢你的帮助！

**Comment by opfanswyx** [comment]
> > > @opfanswyx 发现您[新的地址](https://atticuslab.com/2020/07/js-sequence-diagrams-test/)正常显示了，请问您修改了什么设定呀？
> > > ![image](https://user-images.githubusercontent.com/1907178/86400712-1eace980-bc77-11ea-9ad1-3a32c892791a.png)
> > 
> > 
> > 您好，首先还是要非常感谢你的帮助，抱歉今天才更你说，还是看了你在hugo的提问，感觉是高亮js的问题，我们blog的配置文件`config.toml`中默认的是go编写的`Chroma`，即`pygments`的那个高亮，同时`config.toml`还有另一个高亮选项`highlight.js`，而chroma的`pygments`与`highlight.js`不能同时开启，且只有开启了`highlight.js`这个才会有流程图。
> > 进行了一些列如下选项的排列组合测试，发现是下面的配置，流程图即可正常使用哈：
> > ```
> > pygmentsOptions = ""
> > ptgmentsCodefences = false
> > pygmentsUseClasses = false
> > pygmentsCodefencesGuessSyntax = false
> > 
> > highlightInClient = true #这个在下边
> > ```
> 
> 果然可以了，谢谢你的帮助！
> 我最后把所有`pygments`相关的设置都注释掉了只留下`highlightInClient `：
> 
> ```
> # pygmentsOptions = ""
> # ptgmentsCodefences = false
> # pygmentsUseClasses = false
> # pygmentsCodefencesGuessSyntax = false
> 
> highlightInClient = true #这个在下边
> ```

恭喜，那关闭问题了哈
