### ISSUE TITLE
修改表格样式无效

### ISSUE THREAD

**Issue by xiaohao890809** [olOwOlo/hugo-theme-even#283]
我想把表格调为居中模式：

margin: 10px 0; 改为 0 auto

  .table-wrapper {
    overflow-x: auto;

    > table {
      max-width: 100%;
      margin: 0 auto;
      border-spacing: 0;
      box-shadow: 2px 2px 3px rgba(0,0,0,.125);

结果运行后没有效果呢？？

**Comment by wu0407** [comment]
我修改主题的背景色，也没有效果。最后发现是因为主题目录下面`resources/_gen/assets/scss/sass/main.scss_xxx`,缓存了css的文件导致--使用hugo正常版本会遇到，而使用hugo extend版本没有这个问题。

**Comment by olOwOlo** [comment]
嗯，同上，实际上不是缓存，非 extend 版本是不支持编译 scss 文件，所以 fallback 到了默认文件
