### ISSUE TITLE
footer 中的相关 icon 在 Chrome 中不显示，但是在 Firefox、Edge 浏览器中都正常显示

### ISSUE THREAD

**Issue by Spongecaptain** [olOwOlo/hugo-theme-even#288]
![image](https://user-images.githubusercontent.com/48505670/86762303-23a7d980-c079-11ea-8add-b627366a14c2.png)
这是我的个人博客，你可以使用 Chrome 浏览器访问试试:http://spongecaptain.cool/

**Comment by guyueshui** [comment]
![screenshot-20200709-10-01-02](https://user-images.githubusercontent.com/12670826/86988591-2adefc80-c1cb-11ea-81ed-f63a95f70b16.png)
chromium正常显示～

**Comment by Spongecaptain** [comment]
@guyueshui  最终发现是 AD block 的配置不同导致的，😓 so closed.
