### ISSUE TITLE
image加上边框

### ISSUE THREAD

**Issue by timedreamer** [olOwOlo/hugo-theme-even#30]
hello！有个小白问题，我想给markdown的图片都加上边框，请问怎么设置啊？

我尝试在_custom.scss里加入一下代码, 好像并没有效果。

多谢！

```
img {
  max-width: 100%;
  height: auto;
  display: inline-block;
  vertical-align: middle;
  border: 5px solid;
  padding: 15px;
}
```

**Comment by timedreamer** [comment]
我看到你写的
>如果你更改了 `/src/` 目录下的任意文件，你需要重新编译它们。

是不是我需要重新编译？

运行一下？
```
cd ./themes/even/src/
npm install
npm run build
```

**Comment by olOwOlo** [comment]
[CSS 优先级](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Specificity)

[修改点](https://github.com/olOwOlo/hugo-theme-even/blob/33594c0d1307e1aad56823a7ac5ba6bb18a5d294/src/css/_partial/_post/_content.scss#L42-L45)

需要重新编译

**Comment by timedreamer** [comment]
Thanks a lot!
