### ISSUE TITLE
如何让```mermaid生成class="language-mermaid"不是class="language-fallback"

### ISSUE THREAD

**Issue by leejunj** [olOwOlo/hugo-theme-even#311]
第一次在Github Page建站用了hyde主题，现在尝试改用Even，但是发现文本中用
```mermaid
```
这种写法在最终网页中生成的结构是 <div class="language-fallback">，之前用的hyde会生成<div class="language-mermaid">，然后查询language-mermaid类渲染局部。

虽然可以用 {{< mermaid >}} 也能定位部分区域，但写起来没有```mermaid方便。

**Comment by daniel-hutao** [comment]
+1
