### ISSUE TITLE
代码序号出现错乱

### ISSUE THREAD

**Issue by VegeBun-csj** [olOwOlo/hugo-theme-even#316]
想问一下，出现这种是哪里配置错了么，我也不知道改了什么，就变成这样，还麻烦大佬指点一下，万分感谢！
![image](https://user-images.githubusercontent.com/39252213/98793134-6c660980-2442-11eb-9f7a-5b97c54ca292.png)

**Comment by panda-z** [comment]
Syntax highlightings are conflicted between highlight.js and chroma. 

Just emove the following line in your config.toml. It will disable highlight.js.

```toml
highlightInClient = true
```

**Comment by VegeBun-csj** [comment]
ok，thank you very much . it works!
