### ISSUE TITLE
Wrong line break in the middle of a link 

### ISSUE THREAD

**Issue by do-me** [olOwOlo/hugo-theme-even#321]
When a Link is at the end of a line the line break will be in the middle of the word. The word "Torpy" which is just an ordinary link is wrongly split up.
`[Torpy](https://github.com/torpyorg/torpy)`

![Screenshot](https://user-images.githubusercontent.com/47481567/100084130-aa9ff780-2e4a-11eb-8a20-e127669ba486.jpg)

For reproduction you can create a new post and use the following text:
```
[Fast Instagram Scraper](https://github.com/do-me/fast-instagram-scraper) was designed to be fast and efficient with the perk of using the TOR network powered by [Torpy](https://github.com/torpyorg/torpy).
```

**Comment by panda-z** [comment]
Remove the following line would fix the problem.

https://github.com/olOwOlo/hugo-theme-even/blob/da4320e8a56343ad37a4604e61915675fa18a270/assets/sass/_partial/_post/_content.scss#L44

**Comment by do-me** [comment]
Thanks a lot! Fixed it :)
