### ISSUE TITLE
[feature request] ga4 support

### ISSUE THREAD

**Issue by jiacai2050** [olOwOlo/hugo-theme-even#323]
- https://support.google.com/analytics/answer/10269537
- https://developers.google.com/analytics/devguides/collection/ga4/basic-tag?technology=gtagjs

**Comment by CyrusYip** [comment]
A workaround for implementing GA4 in Hugo: [Google Analytics 4 in Hugo](https://gist.github.com/zjeaton/42246742cdaf2fb46400d04c2eba9a8a)
