### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by alpha-baby** [olOwOlo/hugo-theme-even#331]
// 中间部分是我的md文件
---

title: "centos终端美化配置"
date: 2020-05-09T18:30:09+08:00
lastmod: 2021-01-09T18:30:09+08:00

---

# centos7.8

### 更换阿里源

1. 进入yum文件夹

```bash
cd /etc/yum.repos.d/
```
// 中间部分是我的md文件

### hugo 最新版，老版本也试过

![image](https://user-images.githubusercontent.com/47237632/104090012-868b5f00-52ae-11eb-92c5-3046d241f2b7.png)

然后代码这里就会出现这样，希望大佬们修复下。

**Comment by olOwOlo** [comment]
看起来你同时用了 highlight.js 和 Chroma，把 highlightInClient 关掉就行
