### ISSUE TITLE
How can I enable ligatures in code blocks?

### ISSUE THREAD

**Issue by ClSlaid** [olOwOlo/hugo-theme-even#332]
I adjusted font in `/assets/sass/_custom/_custom.sass` and changed `$code-font-family` to <a href="https://picaq.github.io/sarasa/">`Sarasa Mono SC`</a>. However its font ligature feature doesn't work.
Is there any way to support font ligatures?
Since I know few about front-end, I sincerely persuade you, dear contributors, to support `font ligatures` in future releases.

**Comment by olOwOlo** [comment]
You should load the font into html first, or install it on your pc. see https://stackoverflow.com/questions/2237540/how-do-i-load-external-fonts-into-an-html-document
