### ISSUE TITLE
Make mathjax available on more sections

### ISSUE THREAD

**Issue by ClSlaid** [olOwOlo/hugo-theme-even#333]
I tried using `mathjax` in `logotitle` and it worked well.

![image](https://user-images.githubusercontent.com/44747719/105988589-d6ee2380-60da-11eb-9655-ffbef0034cfe.png)

![image](https://user-images.githubusercontent.com/44747719/105988614-e0778b80-60da-11eb-9f49-7a92cf30328f.png)

However, after switching to other sections (e.g. Archieves, etc.) `mathjax` doesn't work.

![image](https://user-images.githubusercontent.com/44747719/105988891-4b28c700-60db-11eb-9f9d-583ad0ad5335.png)

How can I make it works on other sections?

**Comment by olOwOlo** [comment]
An upstream(mathjax) issue. I guess not all html element will be pick up.

**Comment by ClSlaid** [comment]
only when section showing article content, mathjax appear to work. Maybe the code loading mathjax is within article, is that right? Then by picking it out from article and puting in in the head tag do solve the problem.

**Comment by ClSlaid** [comment]
> An upstream(mathjax) issue. I guess not all html element will be pick up.

My new pull request fixed this problem and add new features to your theme.
I'll be appreciate if you can review and merge it to your project. :)
