### ISSUE TITLE
小功能建议

### ISSUE THREAD

**Issue by Deecyn** [olOwOlo/hugo-theme-even#339]
主题很简洁美观，很赞。还有一点功能小建议：

- 希望集成搜索功能，可以搜索站内的内容，例如主题 [hugo-LoveIt](https://hugoloveit.com/) 。
- 代码块：希望增加一键复制代码、折叠代码块功能，这样当代码较长时会友好很多。

**Comment by lryong** [comment]
另外想提个 Feature Request:  RSS 订阅完后，能否直接推送整篇文章，而不只到 `<!--more-->` 标签前内容

**Comment by sdvcrx** [comment]
@lryong 可以直接复制这个文件放到项目根目录 `layouts/index.rss.xml` ，就可以输出全文RSS

https://github.com/sdvcrx/hugo-theme-even/commit/567b9c10c2bf9fdae7bffdd5ae294d0f37e0fd16

**Comment by lryong** [comment]
> @lryong 可以直接复制这个文件放到项目根目录 `layouts/index.rss.xml` ，就可以输出全文RSS
> 
> [sdvcrx@567b9c1](https://github.com/sdvcrx/hugo-theme-even/commit/567b9c10c2bf9fdae7bffdd5ae294d0f37e0fd16)

不过貌似改了 layout 后， 订阅看不到内容， 我暂时先改回去了
