### ISSUE TITLE
hugo-search-fuse-js配置search功能失败

### ISSUE THREAD

**Issue by wangxinzhi0** [olOwOlo/hugo-theme-even#345]
你好，我按照[issues289](https://github.com/olOwOlo/hugo-theme-even/issues/289)配置了搜索功能。遇到了一个不能解决的情况，在本地hugo server中可以搜索成功，如图所示
![](https://user-images.githubusercontent.com/45959771/118247352-ac7f7500-b4d5-11eb-88bb-0b2d4d132195.png)

但是上传之后访问时[https://wangxinzhi0.github.io/search/](https://wangxinzhi0.github.io/search/)，手机端qq浏览器等可以搜索，但是chrome、Edge等浏览器搜索时“表单不安全”，没有返回搜索结果，如图所示
![](https://user-images.githubusercontent.com/45959771/118247632-f9fbe200-b4d5-11eb-817f-058b811265d3.png)

我尝试了很久，不知道该怎么解决，希望您能抽空解答下我的疑惑，谢谢！

**Comment by lryong** [comment]
@wangxinzhi0 抱歉，我没关注这个项目，现在才看到这个 issue。

这个得看下你的 hugo-theme-even 的博客配置、 或者 Git Page 的配置是否有问题（或者浏览器强制 HTTPS ）。

我的[个人博客](https://blog.herbert.top) 之前启用 HTTPS 后， 因为没有修改 even 的配置，导致部署到 [netlify](https://app.netlify.com/) 失败

可以参考下： https://github.com/kaushalmodi/hugo-search-fuse-js/issues/12
