### ISSUE TITLE
如何更改标签前缀

### ISSUE THREAD

**Issue by Aquaakuma** [olOwOlo/hugo-theme-even#346]
文末的标签都带一个"#"，想把这个"#"改成别的符号，比如🏷️

**Comment by zhangwenboNB** [comment]
在even\assets\sass\_partial\_post\_footer.scss文件中修改.post-tags的content值即可
  .post-tags {
    padding: $post-tags-padding;

    a {
      margin-right: 5px;
      color: $theme-color;
      word-break: break-all;

      &::before {
        content: '🏷️';
      }
    }
  }
