### ISSUE TITLE
关于flow绘制插件渲染

### ISSUE THREAD

**Issue by sslyxhz** [olOwOlo/hugo-theme-even#35]
之前在hexo上有使用了两款插件，直接以markdown生成UML图，简单的例子生成顺序图：
```sequence
Alice->Bob: Hello Bob, how are you?
Note right of Bob: Bob thinks
Bob-->Alice: I am good thanks!
```

有空能否考虑一下移植支持？项目链接在此：
- [hexo-filter-sequence](https://github.com/bubkoo/hexo-filter-sequence)
- [hexo-filter-flowchart](https://github.com/bubkoo/hexo-filter-flowchart)

**Comment by olOwOlo** [comment]
只能在前端渲染，这两天加上~
- [bramp/js-sequence-diagrams](https://github.com/bramp/js-sequence-diagrams)
- [adrai/flowchart.js](https://github.com/adrai/flowchart.js)
