### ISSUE TITLE
googleAnalytics，建议支持一下v4呀

### ISSUE THREAD

**Issue by KevinBlandy** [olOwOlo/hugo-theme-even#352]
v4版本的code，开头不是: UA
![image](https://user-images.githubusercontent.com/17979625/121800958-4bc79180-cc67-11eb-9ebd-deb684c8d4eb.png)

**Comment by xiantang** [comment]
https://github.com/olOwOlo/hugo-theme-even/pull/348

**Comment by xiantang** [comment]
> v4版本的code，开头不是: UA
> ![image](https://user-images.githubusercontent.com/17979625/121800958-4bc79180-cc67-11eb-9ebd-deb684c8d4eb.png)

你可以用我fork 的 仓库https://github.com/xiantang/hugo-theme-even
