### ISSUE TITLE
请教几个问题！

### ISSUE THREAD

**Issue by real-nicholas** [olOwOlo/hugo-theme-even#371]
你好，我想知道你的blog中的图表是怎么实现的，在Markdown中如何使用？

图表，如下图：
<img width="815" alt="Screenshot 2021-10-23 at 13 07 59" src="https://user-images.githubusercontent.com/29486126/138546596-ac228d63-7a02-4042-9a25-db770ea8cbb2.png">

**Comment by syheliel** [comment]
在loveit主题中有关于如何使用echart的[说明](https://hugoloveit.com/theme-documentation-extended-shortcodes/#6-echarts)，你可以看一下是否能做出博客中的效果

**Comment by syheliel** [comment]
在该issue #64  中提出了相同的问题，但所给的网址现在打不开了。不过可以确认的是所用的技术是echart

**Comment by real-nicholas** [comment]
@syheliel 谢谢！
