### ISSUE TITLE
TOC开启目录后， 当[^code] 标签时， {{.TableOfContents}} 内容渲染导致生成两个重复的id，从而无法跳转

### ISSUE THREAD

**Issue by huxiyu** [olOwOlo/hugo-theme-even#39]
例如：
使用[^code]，导致内容和目录都生成了 ***id="fnref:code"***

```
<sup class="footnote-ref" id="fnref:code"><a href="#fn:code">2</a></sup></a></li>
```

[^code]:  
```
<a class="footnote-return" href="#fnref:code"><sup>[return]</sup></a></li>
```

无法返回了。

**Comment by huxiyu** [comment]
而且目录中的这个就不要渲染出超链接 ``<a>`` 了，去掉或者纯字符。

**Comment by olOwOlo** [comment]
没用过这个标签呢，麻烦指点一下怎么用，给段例文让我重现一下 = =

**Comment by huxiyu** [comment]
主要是这个[^]标签出现在目录的标题中造成的。 

[例子](https://www.zybuluo.com/mdeditor#1064675)

#### 1. 里面的这行： `### 2. 书写一个质能守恒公式[^LaTeX]`  
这个标签 [^LaTeX] 生成的代码是
 ```<a href="#fn:latex" id="fnref:latex" title="查看注脚" class="footnote">[1]</a>```
然后这个三级标题会在目录中再次渲染出现同样的代码。就出现两个 `id="fnref:latex"` 了

#### 2. 结尾的这行：
```
[^LaTeX]: 支持 **LaTeX** 编辑显示支持，例如：$\sum_{i=1}^n a_i=0$， 访问 [MathJax][4] 
参考更多使用方法。
```
点击结尾中的返回图标，图标的url是 `https://www.zybuluo.com/mdeditor#fnref:latex`
因为上面出现了两个`id="fnref:latex"`，就不会跳了。

**Comment by olOwOlo** [comment]
这是 hugo 渲染出来的结果，你可以去给他们报告这个问题~~
