### ISSUE TITLE
开启mathjax，当出现两个以上时_{}时解析有问题

### ISSUE THREAD

**Issue by huxiyu** [olOwOlo/hugo-theme-even#40]
正确`$$A_{k}{G_i}$$`

错误`$$A_{k}{G_{i}}$$`，将两个 _ 解析成了`<em>`，结果是`<p>$$A<em>{k}{G</em>{i}}$$</p>`

而且这样也是正确的 `$$A_k{G_i}$$`

**Comment by olOwOlo** [comment]
两个 `_` 是 markdown 语法，用转义字符 `\_` 试试

**Comment by huxiyu** [comment]
vscode或有些网站的mathjax是不用`\_`转义的。不同环境下转换起来很崩溃。

看了下官网有多种解决方法：
https://gohugo.io/content-management/formats/#mmark

第一种我使用mmark，但会导致页面toc目录无法显示。

```
---
title: My Post
date: 2017-04-01
markup: mmark
---
```

另一种方法修改代码还没试...

**Comment by huxiyu** [comment]
或者再增加个 KaTeX ，代替 MathJax
http://nosubstance.me/post/a-great-toolset-for-static-blogging/

**Comment by olOwOlo** [comment]
可以试试在 mathjax 之前加入这段代码~
```js
var postContainer = document.querySelector('.post .post-content');
postContainer.innerHTML = postContainer.innerHTML.replace(/\$\$.*(?:<em>.*<\/em>.*)+\$\$/g, function (match) {
  return match.replace(/<\/?em>/g, '_');
});
```

**Comment by huxiyu** [comment]
@olOwOlo 这个替换的方式可以用

**Comment by MACDfree** [comment]
@olOwOlo  使用js只是替换掉em标签，但现在遇到如下问题：`$$\left\{ { x }_{ 1 },{ x }_{ 2 },{ x }_{ 3 },...{ x }_{ n } \right\}$$` 其中`\{`被转义为`{`，导致公式解析出错，现在我的解决方式为自定义一个shortcode，如下：

```
{{ if len .Params | eq 1 }}{{ .Get 0 }}{{ end }}
```

md中公式替换为：

```
{{< pure "$$\left\{ { x }_{ 1 },{ x }_{ 2 },{ x }_{ 3 },...{ x }_{ n } \right\}$$" >}}
```

**Comment by hoasxyz** [comment]
我遇到了同样的问题，可是您的解释我有些看不懂，可以给些提示吗？ @MACDfree

**Comment by MACDfree** [comment]
此问题问题比较久远，有点记不清了。大致原因是转移导致公式出错，解决问题的目标就是如何防止被转义，我的做法是利用hugo里的 [shortcode](https://gohugo.io/templates/shortcode-templates/) 功能，将公式通过shortcode输出，可以防止被转义。

做法上就是个性化even主题
![image](https://user-images.githubusercontent.com/3363410/57831545-05817900-77e8-11e9-8a3c-29892d5e4447.png)

使用
![image](https://user-images.githubusercontent.com/3363410/57831623-382b7180-77e8-11e9-852b-12ef5d09e8ee.png)

**Comment by hoasxyz** [comment]
@MACDfree 学到了，谢谢~

**Comment by zzrrxx** [comment]
这个问题困扰了我好久， 刚刚在 gohugo.org/doc/tutorials/mathjax/ 看到可以通过使用 <div> 将数学公式包起来结局，希望能帮助到同样有这个问题的人

**Comment by scarletsky** [comment]
升级 hugo 后，hugo 默认的 markdown 解析器换成了 goldmark，但这会导致用 `<div>` 包围的公式显示不了，要换回 blackfriday 才行：

```
[markup]
defaultMarkdownHandler = "blackfriday"
```

**Comment by yesiare-cn** [comment]
katex 
```
\_
```
所有的反斜杠都被转义了，导致katex解析错误，有办法解决么？

**Comment by timerring** [comment]
Try this config:

https://github.com/gohugoio/hugo-goldmark-extensions?tab=readme-ov-file#passthrough-extension

sample:
```
[markup.goldmark.extensions.passthrough]
    enable = true
[markup.goldmark.extensions.passthrough.delimiters]
    block = [['\[', '\]'], ['$$', '$$']]
    inline = [['\(', '\)']]
```

It works.
