### ISSUE TITLE
some requst  js missing

### ISSUE THREAD

**Issue by bob1118** [olOwOlo/hugo-theme-even#400]
jquery.min.js ,slideout.min.js,jquery.fancybox.min.js not found!
here is request url.
https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js
https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js
https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js

even are still alive ?

**Comment by dysoso** [comment]
The same question
The following links cannot be accessed, causing the page to load slowly
How to solve this problem?
--------------------------------------------------------------------
https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css
https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js
https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js
https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js

**Comment by dysoso** [comment]
找到临时解决办法了,亲测可行:
批量将图片或其它静态资源链接中的 cdn.jsdelivr.net 替换为 fastly.jsdelivr.net 即可，等待官方将该问题修复后，再替换回来
原文:https://blog.csdn.net/jiyc2008/article/details/124879647

**Comment by bob1118** [comment]
cdn.jsdelivr.net avialiable now .

**Comment by bob1118** [comment]
issue closed.

**Comment by bob1118** [comment]
cdn.jsdelivr.net avialiable now .
issue closed.
