### ISSUE TITLE
突然间无法通过 hugo 渲染 md 文件

### ISSUE THREAD

**Issue by yibie** [olOwOlo/hugo-theme-even#401]
错误提示：

`Error: Error building site: failed to render pages: render of "page" failed: "/Users/chenyibin/学无止境@一点一滴/themes/even/layouts/_default/baseof.html:14:5": execute of template failed: template: post/single.html:14:5: executing "post/single.html" at <partial "head.html" .>: error calling partial: "/Users/chenyibin/学无止境@一点一滴/themes/even/layouts/partials/head.html:13:72": execute of template failed: template: partials/head.html:13:72: executing "partials/head.html" at <safeHTML>: error calling safeHTML: unable to cast []string{"Steve Chan"} of type []string to string
Total in 126 ms
`

不太理解这是什么意思，麻烦了，谢谢。

**Comment by shockerli** [comment]
将Hugo从0.88升级到0.99后同遇到。可理解为新版本Hugo放弃了一些模板变量，而模板没有跟进，就GG了。作者好久没维护了，我之前提的PR都半年了还没合并，所以只能用老版本的Hugo。
