### ISSUE TITLE
frontmatter不支持summary?

### ISSUE THREAD

**Issue by vinurs** [olOwOlo/hugo-theme-even#41]
如题，我在markdown里面增加了frontmatter：
`summary = "xxxx"`
但是没有解析出来，但是readmore之前的确实是能够解析出来

**Comment by olOwOlo** [comment]
并没有这个参数，你想要什么效果 ❓

**Comment by vinurs** [comment]
我看你代码里面有这段代码，就是readmore之前的文字吧
![image](https://user-images.githubusercontent.com/2130033/37320817-703eee24-26b0-11e8-9684-fb031b90a2b1.png)
可能是之前使用的主题的特性吧，就是有summary这个frontmatter的时候就取代readmore之前的文字显示。

**Comment by olOwOlo** [comment]
没有这个功能呢，这个代码是让 `summary.html` 这个模板渲染的意思

**Comment by vinurs** [comment]
那frontmatter里面的description这个字段有解析吗？这个是不是也是readmore的功能？
@olOwOlo 私信我邮件一下，有事情找你帮忙一下。

**Comment by olOwOlo** [comment]
- 有解析，关于 front-matter，[README](https://github.com/olOwOlo/hugo-theme-even/blob/master/README-zh.md#front-matter) 里已经说明过了
- > **没有这个功能呢**
- 在这里说就好了

**Comment by wangpeng0531** [comment]
Front Matter是支持summary这个参数的，官方文档有说明，支持三种摘要方式：
1.默认摘要：取文章前70个文字
2.手动摘要：定义标记，该标记之前显示为摘要文本
3.自定义摘要：即独立于文章内容，使用summary参数。
但是需要注意的是，标记是优于summary参数的，即使用summary参数需要删除more标记。
