### ISSUE TITLE
<!--more-->能设置成默认的么？用了之后，在主页后面的就不显示了

### ISSUE THREAD

**Issue by jinleileiking** [olOwOlo/hugo-theme-even#43]
有个选项来控制？

**Comment by jinleileiking** [comment]
我试了一下，more会让more之前的用markdown渲染。

这样就导致，我们需要添加more来控制主页显示的文字。----这个感觉是不合理的。更合理的做法是框架根据文字数目，自动渲染一些markdown

主页不可以自动控制要渲染的文字数目么？是不是不好做？

**Comment by olOwOlo** [comment]
see https://gohugo.io/content-management/summaries/

**Comment by jinleileiking** [comment]
赞。多谢
