### ISSUE TITLE
Can't be run in hugo version: 0.127.0 

### ISSUE THREAD

**Issue by junxxx** [olOwOlo/hugo-theme-even#434]
在mac里运行报错。在Github的Action里也报同样的错误。
hugo v0.127.0+extended darwin/arm64 BuildDate=2024-06-05T10:27:59Z VendorInfo=brew

ERROR deprecated: .Site.RSSLink was deprecated in Hugo v0.114.0 and will be removed in Hugo 0.128.0. Use the Output Format's Permalink method instead, e.g. .OutputFormats.Get "RSS".Permalink
WARN  deprecated: .Site.GoogleAnalytics was deprecated in Hugo v0.120.0 and will be removed in a future release. Use .Site.Config.Services.GoogleAnalytics.ID instead.
WARN  deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0 and will be removed in a future release. Use .Site.Config.Services.Disqus.Shortname instead.
WARN  The author key in site configuration is deprecated. Use params.author.name instead.
Built in 53 ms
Error: error building site: logged 1 error(s)

我想，应该是hugo版本升级导致的。

**Comment by guixian001** [comment]
有些配置的变量变了，我刚刚 fork 了一份，自己改了改
