### ISSUE TITLE
home 界面能否按时间发布排序？

### ISSUE THREAD

**Issue by xlk3099** [olOwOlo/hugo-theme-even#44]
home 界面列出来的文章能按时间排序吗？

**Comment by xlk3099** [comment]
不知为何，我本地搭建的没有按时间排序。。。
<img width="1015" alt="screen shot 2018-03-19 at 10 57 41 am" src="https://user-images.githubusercontent.com/1768412/37575879-73ef68ce-2b64-11e8-90d1-9f372fb301f3.png">

**Comment by olOwOlo** [comment]
see https://gohugo.io/templates/lists/#order-content
