### ISSUE TITLE
更改添加 comment 评论的页面

### ISSUE THREAD

**Issue by zhaozhiyuan1989** [olOwOlo/hugo-theme-even#50]
希望阿婆主考虑将 comment.html 的插入位置由 baseof.html 改为 partial/post/single.html ，这样可以保证只在博文中添加评论功能，避免在 about 等不想加评论的地方出现评论框。

**Comment by olOwOlo** [comment]
也有希望在 about 页面中显示评论的，评论已经只会在内容页面出现了，如果你不想它在 about 页出现，在 [front-matter](https://github.com/olOwOlo/hugo-theme-even/blob/master/archetypes/default.md) 里指定：

```yaml
comment: false
```
