### ISSUE TITLE
如何使disqus评论插件只出现在post页面？

### ISSUE THREAD

**Issue by AlexJinlei** [olOwOlo/hugo-theme-even#56]
打开disqus功能以后，所有页面的底部都会出现评论框。Home，Archives 等页面下并无添加评论功能的必要。请问如何能关闭除post正文之外其他页面下的评论功能？

**Comment by olOwOlo** [comment]
是不会加载的，你没有修改模板文件？根目录下的 layout 目录下是否有不相关的文件？

**Comment by AlexJinlei** [comment]
@olOwOlo 噢！是我犯了个错误。我在comments.html里面加了一段disqus嵌入代码，这段代码会在所有生成的页面里加载评论框。刚才仔细看了comments.html的内容才发现disqus功能已经集成好了。多谢作者 :)

P.S. : 在这里也顺便提醒一下其他的用户。要添加disqus评论插件只需更改config.toml文件里disqusShortname的值即可，不需要按照disqus官网的说明添加代码。另外，在本地localhost生成的网页不会加载评论框，这一点是comments.html里特意做的限制。我当时就是在localhost里看不到评论框才改了comments.html文件。
