### ISSUE TITLE
如何指定output文件?

### ISSUE THREAD

**Issue by Ailen1988** [olOwOlo/hugo-theme-even#59]
**_如何指定output文件?_**
以及配置中的
`
# 将下面这段配置取消注释可以使 hugo 生成 .md 文件
# Uncomment these options to make hugo output .md files.
[mediaTypes]
  [mediaTypes."text/plain"]
    suffix = "md"

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
 taxonomyTerm = ["HTML"]
`
**是做什么用的?**

请大家指导.

**Comment by olOwOlo** [comment]
- https://gohugo.io/getting-started/configuration/#all-configuration-settings

**Comment by Ailen1988** [comment]
我已经在config.toml增加了
publishDir = "public"
`

**Comment by olOwOlo** [comment]
生成静态文件的命令是 
```bash
hugo
```

https://blog.olowolo.com/post/hugo-quick-start/

**Comment by Ailen1988** [comment]
谢谢, 已经有了, 之前我看过文章并执行过hugo, 但是没有生成. 
后来发现原因是因为, 我手动创建了public, 并且没有修改权限. 我删了手动创建的public, 再执行hugo命令, 就生成了静态文件.

再次感谢.
