### ISSUE TITLE
Make robots.txt agnostic of trailing slash in baseURL

### ISSUE THREAD

**Issue by sanjayts** [olOwOlo/hugo-theme-even#6]
Hello,

Just noticed that the `Sitemap` URL created in `robots.txt` depends on whether we have a trailing slash in `baseURL`. It might be much easier to let Hugo figure it out by using `absURL`? https://gohugo.io/functions/absurl/

I'll send a PR in case you are interested in making this change. BTW, thanks for this theme. :)

**Comment by olOwOlo** [comment]
Thank you.   ̋(ˊ•͈ ꇴ •͈ˋ)
