### ISSUE TITLE
Twitter link not working

### ISSUE THREAD

**Issue by valankar** [olOwOlo/hugo-theme-even#60]
I have in config.toml:

`c-twitter = "https://twitter.com/valankar"`

But I don't see any Twitter icon at the bottom.

**Comment by olOwOlo** [comment]
It looks like you have resolved it.

**Comment by valankar** [comment]
Hm, what do you mean? I still do not see it showing up on my blog.

**Comment by olOwOlo** [comment]
![snipaste_20180526_220630](https://user-images.githubusercontent.com/26087907/40576985-14d840c4-6131-11e8-94de-13ac3a9233db.png)

I saw it on your website ❓ 

Is your domain name `steropes.feralhosting.com` ❓

Which browser are you using ❓ 

Do you install ad blocker plugins such as `AdBlock` ❓

**Comment by valankar** [comment]
Hi, yes that is my site.

I am using Safari with AdGuard. Indeed, when I turn AdGuard off the Twitter link works. It also works in Chrome with uBlock Origin. So it seems AdGuard doesn't like it for some reason.

I can't find any AdGuard logs. So will close this.
