### ISSUE TITLE
Embed Gist show in a wrong style

### ISSUE THREAD

**Issue by NineRec** [olOwOlo/hugo-theme-even#61]
When I add embed gist in my MD file, the compiled page cannot show it correctly.
For Example: 
```
Liz Rice 的代码如下：

<script src="https://gist.github.com/julz/c0017fa7a40de0543001.js"></script>
```

The compiled page shows that the gist style `.gist .blob-num {width: 1%;}` conflicted with the style `.post .post-content .highlight td {width: 100%;}` in _code.scss:72.

**Comment by olOwOlo** [comment]
Fixed. Feel free to reopen if there are still problems.
