### ISSUE TITLE
内网使用hugo，可否考虑提供将js/css资源文件集成到even中 (use hugo intranet, maybe provide a package with js/css asset built in)

### ISSUE THREAD

**Issue by morya** [olOwOlo/hugo-theme-even#63]
hugo很方便，现在内网环境使用，但js/css资源文件都是自动使用cdn，
导致js-sequence无法展示。

我本地hack了一个，能用，想请教是否可以给个pull request.

hugo is good, I use it in intranet. Browser can't download some js/css files.
js-sequence / flowchart are not working...

I hacked on copy, should I send a PR?

**Comment by olOwOlo** [comment]
可以的，请使用现在定义的 CDN 上下载下来的版本
