### ISSUE TITLE
使用多个section时，标签/分类里不是”post“下的帖子定义的标签/分类下无法显示帖子列表

### ISSUE THREAD

**Issue by keithmork** [olOwOlo/hugo-theme-even#65]
标题写得有点绕，背景如下：

- 我的博客使用了多个section，例如 `post` 和 `game`，把技术类文章和其他文章分开。
- 每个section下的文章都定义了一些标签和分类
- 但在右上菜单的 tags、categories 里，只有 post 下的标签/分类点进去能看到帖子列表，其他section的标签/分类点进去是空白页

我发现 `layouts/_default/section.html` 和 `layouts/_default/taxonomy.html` 里写死了section：

```
{{- $paginator := .Paginate (where .Data.Pages.ByDate.Reverse "Type" "post") .Site.Params.archivePaginate }}
```

把条件去掉后问题就解决了：

```
{{- $paginator := .Paginate .Data.Pages.ByDate.Reverse .Site.Params.archivePaginate }}
```

请问当初是出于什么考虑写死的？我有没有遗漏了什么？

我的博客已经按上面那样改了，现在来自任何section的分类/标签点进去都能看到列表：

http://keithmo.me/tags/

**Comment by olOwOlo** [comment]
确实有这个问题呢，当初就是为了留作扩展 section 的，现在看来好像不太对~~
话说你是为 game 这个 section 复制了一份模板嘛？照理说应该是和 about 页面一个模板的啊

**Comment by keithmork** [comment]
是的，把原来post里的东西复制到自己的layout下。

这块暂时没想到有什么通用的解决方法，像我这样把多个section完全分开故意藏着的人可能比较少，更多的人估计会按官网例子把section取名“posts”，然后发现怎么各种高大上的功能都看不到：）

**Comment by retp** [comment]
+1
