### ISSUE TITLE
如果你更改了 /src/ 目录下的任意文件，你需要重新编译它们，不知道win下需要装什么东西？请教

### ISSUE THREAD

**Issue by hxf3591126** [olOwOlo/hugo-theme-even#69]
如果你更改了 /src/ 目录下的任意文件，你需要重新编译它们
cd ./themes/even/src/
npm install
npm run build

不知道win下需要装什么东西？请教
目前用的时候，提示是没有这个命令。
npm，win下怎么装？

**Comment by hxf3591126** [comment]
额，好像知道了。要装这个？
https://nodejs.org/dist/v8.11.2/node-v8.11.2-x64.msi

**Comment by olOwOlo** [comment]
![yes](https://user-images.githubusercontent.com/26087907/40698133-28bebbfa-6400-11e8-9b6e-97bc2f7ee503.jpg)
