### ISSUE TITLE
Error: yaml: line 1: did not find expected key

### ISSUE THREAD

**Issue by shuqian** [olOwOlo/hugo-theme-even#72]
hugo version
Hugo Static Site Generator v0.16-DEV BuildDate: 2016-02-07T01:14:17+08:00

安装了几次都不行，不知道怎么回事
/var/www/hugo$ sudo hugo new about.md
Error: yaml: line 1: did not find expected key

var/www/hugo$ sudo hugo --log
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/404.html:7: function "relLangURL" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/_default/baseof.html:2: function "errorf" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/_default/section.html:1: function "T" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/_default/taxonomy.html:21: function "default" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/_default/terms.html:1: function "T" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/index.html:14: function "T" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/partials/footer.html:17: function "T" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/partials/head.html:18: function "plainify" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/partials/header.html:2: function "relLangURL" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/partials/post/copyright.html:4: function "T" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/partials/post/outdated-info-warning.html:2: function "now" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/partials/post/reward.html:4: function "T" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/partials/post/toc.html:3: function "T" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/partials/slideout.html:3: function "relLangURL" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/post/single.html:8: function "default" not defined
ERROR: 2018/06/03 12:07:59 template.go:350: template: theme/post/summary.html:5: function "default" not defined
ERROR: 2018/06/03 12:07:59 general.go:222: Error while rendering taxonomy category: html/template: "theme/_default/taxonomy.html" is an incomplete template

**Comment by olOwOlo** [comment]
都2018年了，装个新版本吧
https://github.com/gohugoio/hugo/releases
