### ISSUE TITLE
.slideout-panel shouldn't have a min-height

### ISSUE THREAD

**Issue by Jiehong** [olOwOlo/hugo-theme-even#74]
Currently, slideout-panel has a `min-height` of `100vh`.

However, the body has a top border of `3px`.

When the front page is displayed with just 1 article, it creates a useless scroll-bar, as the total height is `100vh + 3px`.

Simply removing this min-height solves the issue, and doesn't seem to break anything that I could see.

If you don't want to remove it, its value should be set to `min-height: calc(100vh - 3px);` instead.

Test done with Firefox 60.0.2 and Chrome 67.0.

**Comment by olOwOlo** [comment]
The `min-height` is for mobile screen, you should not remove it, and I think `100vh` is a correct value.

See also https://stackoverflow.com/questions/34752039/100vh-results-in-scroll-bar
