### ISSUE TITLE
目录项过多时，TOC右侧目录导航无法滚动

### ISSUE THREAD

**Issue by shockerli** [olOwOlo/hugo-theme-even#78]
当文章目录项过多时，右侧TOC目录高度超过浏览器高度，无法滚动

**Comment by olOwOlo** [comment]
设置 `autoCollapseToc: true` 可以自动折叠目录

**Comment by aleafboat** [comment]
@olOwOlo  能控制目录不显示吗？

**Comment by aleafboat** [comment]
toc = true                                                                            # 是否开启目录
不好意思，阅读文档明白了
