### ISSUE TITLE
[Feature request] Possibility to customize highlight.js

### ISSUE THREAD

**Issue by Punie** [olOwOlo/hugo-theme-even#79]
Hi!

Would you consider adding the two following configuration parameters:
- possibility to disable the default highlight.js build provided in order to include a richer one (with support for more languages) in the static/js folder.
- highlighjsTheme : to be able to select one of the highlight.js bundled themes.

I started hacking on this myself and noticed that the highlightjs support in this theme is mostly hardcoded.
I'm looking into making those points customizable from the config.toml. If I come to a usable solution, I'll make a PR.

**Comment by olOwOlo** [comment]
- If you want to load a richer build of `highlight.js`, just put it in `static/lib/highlight.pack.js` at the root of your project.
- Chroma is the default choice  in next release(4.0.0). This feature is already done in next branch (https://github.com/olOwOlo/hugo-theme-even/commit/77101032aa61cad251fbe02476aa6d1e0df24d74).

If you want to try the next branch, please note that there have been some breaking changes, and there may be more breaking changes afterwards. And you need to rebuild the theme.

```bash
# install dependencies
yarn
# build
yarn build
```
