### ISSUE TITLE
华为emui 4.0.1浏览器点击菜单按钮无反应

### ISSUE THREAD

**Issue by RocFang** [olOwOlo/hugo-theme-even#8]
首先感谢作者贡献这么美观的主题 @olOwOlo  

现在在移动端尝试了几台设备，iPad，iPhone， 以及微信内置浏览器都能正常工作，但一个华为手机点击菜单按钮无反应

**Comment by olOwOlo** [comment]
@RocFang 
按照IE和Edge修改了一下，感觉可能是同样的原因。

**Comment by RocFang** [comment]
@olOwOlo 
测试了一下，果然可以了，感谢感谢！
