### ISSUE TITLE
有没有考虑添加最近文章和最新评论？

### ISSUE THREAD

**Issue by Zeeech** [olOwOlo/hugo-theme-even#80]
如题

**Comment by olOwOlo** [comment]
最新评论这个很依赖具体的评论系统啊，而且现在这个布局感觉没什么地方放。

Hugo 有个相似文章，以后看看能不能装上，放在每一篇文章的最后~

**Comment by Zeeech** [comment]
嗯。主题很赞。 确实没有多余的地方放这些东西了。

**Comment by if2012** [comment]
@olOwOlo 相似文章有必要搞一搞

**Comment by resonweb** [comment]
我觉得"最近文章"和"置顶文章"还是很有用的, 可以考虑一下吗?
