### ISSUE TITLE
org-mode格式的情况下，无法生成文章的目录，这个能通过css实现吗

### ISSUE THREAD

**Issue by worldwar2008** [olOwOlo/hugo-theme-even#81]
在mark-down格式的情况下，没啥问题；
但是org-mode的文章格式下，显示不出来目录

**Comment by xianmin** [comment]
hugo 使用的 orgmode 解析器是 https://github.com/chaseadamsio/goorgeous ，
这个解析器不太成熟，从该项目的 issues 板块可以发现，这个解析器有一些 bug，部分语法还不支持。主要问题是，这个项目已经有一段时间没有更新了。

一个替代方案是使用 ox-hugo ，你可以去了解一下。

**Comment by worldwar2008** [comment]
好的。谢谢。
