### ISSUE TITLE
Markdown渲染问题

### ISSUE THREAD

**Issue by zhishiwanwan01** [olOwOlo/hugo-theme-even#84]
你好，最近用markdown使用$$包含公式时，里面的\\换行在渲染成html后就变成了一个\，请问这个可以修改吗？另外我在config.toml里设置了` mathjaxEnableAutoNumber = true `， 但是渲染出来后方程后面并没有标号。

**Comment by olOwOlo** [comment]
- `\` 被转义是 markdown 渲染的问题，你可以换个渲染器，或者用 `\\` 转义，用 shortcode，自己搜搜吧.....
- 标号的配置是 `TeX: {equationNumbers: {autoNumber: "AMS"}},`，至于为什么没有...你需要查阅一下文档，我也不是很懂。

**Comment by zhishiwanwan01** [comment]
目前我在markdown里用'\\\'来换行。请问这个渲染器指的是mathjax吗？另外我能像hugo官网推荐的那样自己配置一个mathjax的config file吗

**Comment by olOwOlo** [comment]
- 我是说 hugo 的 markdown 渲染器，issue 里，google 不少这种问题
- 自行修改[模板文件](https://github.com/olOwOlo/hugo-theme-even/blob/d7fb92fff90b9c23aa20fd1c4d10ac10e168531f/layouts/partials/scripts.html#L59)即可

**Comment by zhishiwanwan01** [comment]
好的，那我查一查，谢谢解答

**Comment by zhishiwanwan01** [comment]
注：https://discourse.gohugo.io/t/solved-prevent-html-escaping-for-latex/13354
