### ISSUE TITLE
Variable theme-color-config not being respected in v0.46 of hugo

### ISSUE THREAD

**Issue by pheonix991** [olOwOlo/hugo-theme-even#85]
I am unable to change the default theme color as of Hugo v0.46 via the variable`theme-color-config`.  Last time I generated my site with Hugo v0.42.2, 2018-07-08 it worked.

You can see the current theme set to "Dark Purple" on my site currently https://blog.fiona.zone.

Example of the site generated with the current version of Hugo with the `theme-color-config` not being respected here:  https://hub.docker.com/r/pheonix991/blog-dot-fiona-dot-zone/

Current version on my laptop running Solus Linux:
```
Hugo Static Site Generator v0.46/extended linux/amd64 BuildDate: 2018-08-01T22:38:20Z
```

Current version in the container(dettmering/hugo-build:latest) used to build the example nginx container:
```
Hugo Static Site Generator v0.46/extended linux/amd64 BuildDate: 2018-08-01T09:11:41Z
```

**Comment by zhishiwanwan01** [comment]
Did you rebuild your src?
```
cd ./themes/even/src/
npm install
npm run build
```

**Comment by olOwOlo** [comment]
![snipaste_20180810_220423](https://user-images.githubusercontent.com/26087907/43962159-8bb4e000-9ce9-11e8-9bf4-e176cee29e7a.png)

Maybe you need a [force refresh](https://www.google.com/search?q=force+refresh) ?

**Comment by pheonix991** [comment]
I needed to rebuild the source.  Thanks zhishiwanwan01!!!
