### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by baddate** [olOwOlo/hugo-theme-even#86]
__I cant update favicon, help!!__

**Comment by olOwOlo** [comment]
>In order to customize the favicon you need to place **all** the following files in the `static` folder at the root of your site, which will overwrite those files in the [`themes/even/static/`](https://github.com/olOwOlo/hugo-theme-even/tree/master/static) folder.
>
>* android-chrome-192x192.png
>* android-chrome-512x512.png
>* apple-touch-icon.png
>* browserconfig.xml
>* favicon.ico
>* favicon-16x16.png
>* favicon-32x32.png
>* manifest.json
>* mstile-150x150.png
>* safari-pinned-tab.svg
>
>A [favicon generator](https://www.google.com/search?q=favicon+generator) can help you generate these files.
