### ISSUE TITLE
post drafts are not recognized

### ISSUE THREAD

**Issue by garfieldnate** [olOwOlo/hugo-theme-even#9]
I followed the directions in the readme to setup the theme, then created a new draft with `hugo new posts/foo.md`. Now when I run `hugo server -D` the site starts and the theme is shown correctly, but the contents in `foo.md` are not shown on the page. How do I create posts for this theme?

**Comment by olOwOlo** [comment]
For this theme, you should use **post** instead of **posts**.

```
hugo new post/foo.md
```

**Comment by garfieldnate** [comment]
Thanks, it works now. The tutorial on hugo's website uses the `posts` directory, and I didn't know that a theme could change this.
