### ISSUE TITLE
Minor css issue?

### ISSUE THREAD

**Issue by ikosmidis** [olOwOlo/hugo-theme-even#92]
Thanks for the great theme. Just getting a minor unwanted behaviour when switching pages from the menu items: there is a very slight move of the content on the right for a few miliseconds, before everything realigns again. This is apparent also in the demo and happens in all browsers and devices I tried it (safari, firefox, ipad, iphone, android phone). It is not a big deal but do you have any idea how I can avoid this behaviour?

**Comment by ikosmidis** [comment]
I am unable to reproduce this after playing with the theme, so I am closing for now. I will re-open only if I can trace it back to a specific setting.

**Comment by olOwOlo** [comment]
Alright, it is a bug, but I don't know how to resolve it.  😢

It looks like a css animations issue.

**Comment by Qfist** [comment]
Well based on my extensive experience and after casting some debugging magic, i figured it out.
Scroll bar is your demon. You have a "loading jerk" problem. Some explanation coming in few minutes , let me just take take the audit screenshots.

**Comment by Qfist** [comment]
First step to reproduce the problem.

Reproduction steps:
1. Try resizing the window to something narrow (800px or so)
2. Switch between pages using the menu.  Pay attention to loading and scroll bar.
_Not so pro tip:  You can also use developer tools for device emulation. :)_

Cause: 
Loading order. Some of your content loads after the page has been rendered. Additional content gets added causing page jerk. 
_That social media code might be the one causing problem._

Possible solutions:

Check loading order of your scripts. 
Check where are you pulling those iconfonts from and their loading order.
Get rid of scroll bar with some css.

Here are some load recording screenshots, showing the page loading . 
You can see the loading order of "Categories" page. Just switch between first two images and you will see the problem. Logo gets loaded last. 


 page , much less frame by frame.
![categories loading 0](https://user-images.githubusercontent.com/2602691/44607321-5e3f5a80-a7f0-11e8-9dfa-c35106c27b24.png)
![categories loading 1](https://user-images.githubusercontent.com/2602691/44607336-6d260d00-a7f0-11e8-8811-46e9d59d1902.png)
![categories loading 2](https://user-images.githubusercontent.com/2602691/44607346-77480b80-a7f0-11e8-99ff-d812d46462d2.png)

**Comment by ikosmidis** [comment]
Thanks @Qfist! It is weird though. I cannot anymore replicate the behaviour in my machine (or it happens too fast for my eyes now?) but it is there when I try in a fresh machine. 
Could it be something of the kind that once caches have been built the transition appears smooth, so an issue with the website waiting loading a remote js every time a transition happens?

**Comment by Qfist** [comment]
Yes that's right, your page gets cached and bug looks intermittent. 
Just empty your cache and you should be able to see it.

**Comment by Qfist** [comment]
If you don't resolve it in the next few days, i will find some time during next week to assist you. :)

**Comment by ikosmidis** [comment]
OK! I think I hacked around this bug by adding

html{ height:101%; }

in _custom.scss and rebuilding. The fact that the problem disappears if there is already a scrollbar in the window (try making the height of the window small) got me curious and the above ensures that a scrollbar is always present.

Looks fine now to me now. @Qfist tests will help to check whether this resolves the issue.

**Comment by Qfist** [comment]
I think i will have some time tomorrow to look into this. :)

**Comment by Qfist** [comment]
Ok i just looked into this. It might be better idea to remove that 101% rule and replace it with:

```html
html {
  overflow-y: scroll;
}
```
Just add it to _custom.scss like you did with previous code and recompile.

That 101% might cause some problems and miscalculations when you get deeper into modifying your site. :)
