### ISSUE TITLE
请教一个问题，修改哪些东西，可以将文章的路由由 post 改为 posts

### ISSUE THREAD

**Issue by Chyroc** [olOwOlo/hugo-theme-even#94]

**Comment by Chyroc** [comment]
如果使用`hugo new posts/xxxx.md`，那么在首页不会看到文章

**Comment by olOwOlo** [comment]
建议阅读一下[文档](https://gohugo.io/content-management/sections/)了解一下 section 你就知道了，至于首页看不到，看看 index.html 这个模板
