### ISSUE TITLE
美丽的olOwOlo，能否考虑增加一个搜索功能呀

### ISSUE THREAD

**Issue by mrzhenggang** [olOwOlo/hugo-theme-even#98]
美丽的olOwOlo，能否考虑增加一个搜索功能呀，文章一多不能搜索不方便查询。

自己搞的太丑了...

感谢！

**Comment by olOwOlo** [comment]
这位大佬 https://github.com/olOwOlo/hugo-theme-even/issues/70#issuecomment-399690060 自己做的我感觉还挺好看的（是指 ta 自己的网站），你可以参考一下，最近不太闲没时间~
