### ISSUE TITLE
显示原始markdown文档

### ISSUE THREAD

**Issue by luozongtong123** [olOwOlo/hugo-theme-even#99]
按照您博客中讲述的方法，不成功啊，链接点进去是404

**Comment by luozongtong123** [comment]
用0.4.3版本的成功了，用0.4.8版本会提示如下信息：
Error: MediaType.Suffix is removed. Before Hugo 0.44 this was used both to set a custom file suffix and as way
to augment the mediatype definition (what you see after the "+", e.g. "image/svg+xml").

This had its limitations. For one, it was only possible with one file extension per MIME type.

Now you can specify multiple file suffixes using "suffixes", but you need to specify the full MIME type
identifier:

[mediaTypes]
[mediaTypes."image/svg+xml"]
suffixes = ["svg", "abc" ]

In most cases, it will be enough to just change:

[mediaTypes]
[mediaTypes."my/custom-mediatype"]
suffix = "txt"

To:

[mediaTypes]
[mediaTypes."my/custom-mediatype"]
suffixes = ["txt"]

Note that you can still get the Media Type's suffix from a template: {{ $mediaType.Suffix }}. But this will now map to the MIME type filename.

**Comment by olOwOlo** [comment]
这是 hugo 的 breaking change， 按照它的错误提示修改就可以了

```toml
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]
```
